### ISSUE TITLE
Get running application list, cross-platform

### ISSUE THREAD

**Issue by egoist** [sindresorhus/module-requests#105]
For example on macOS you can achieve this by running applescript:

```applescript
osascript -e 'tell application"System Events" to get name of (processes where background only is false)'
```

It would be ideal that we can have a cross-platform solution for this:

```js
const appList = require('app-list')

appList().then(list => {
  // ['iTerm2', 'Telegram', 'Sublime Text', ...]
})
```

And maybe more info about the apps too, like `last used time`

**Comment by sindresorhus** [comment]
What do you need it for?

**Comment by egoist** [comment]
@sindresorhus for such feature in Discord:

<img width="135" alt="2017-11-18 5 42 06" src="https://user-images.githubusercontent.com/8784712/32978992-db788f8e-cc87-11e7-9c2d-994d82943548.png">

**Comment by hemanth** [comment]
We could enhance [process-list](https://www.npmjs.com/package/process-list) to support `osx` and it should suffice this use case.

**Comment by yinghang** [comment]
What about this [neekey/ps](https://github.com/neekey/ps)?

**Comment by kevva** [comment]
We already have https://github.com/sindresorhus/ps-list. I think @egoist only want to get apps that are running.

**Comment by nektro** [comment]
While I'm sure it's possible, it shouldn't be.

**Comment by Richienb** [comment]
@egoist I've confirmed it's possible to do this. I'll start working on the module.

**Comment by Richienb** [comment]
I've got some basic logic down. I'll test this a bit before releasing:
https://github.com/Richienb/winds

**Comment by Richienb** [comment]
@egoist I've released [winds](https://github.com/Richienb/winds) with a [passing build](https://travis-ci.com/Richienb/winds/builds/143006401) which resolves this issue.

@sindresorhus You can close issue now.
