### ISSUE TITLE
Multi-key Map

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/module-requests#108]
Do you know of a multi-key map? For example:

```js
const cache = new MultiMap();
cache.set(key1, key2, promise);
cache.get(key1, key2);
cache.has(key1, key2);
```

Demo 1, `.set([key1, key2], value)`: https://runkit.com/bfred-it/multimap-demo/2.0.0
Demo 2, `.set(key1, key2, value)`: https://runkit.com/bfred-it/multimap-demo/3.0.3

Notes:
- almost too flexible, `.get(key1)` returns `Map([key2, value])`, which is not too bad IMHO
- not sure I want to complete/test/publish this 😅 

Tests that it should probably also pass, adjusted:
- https://github.com/zloirock/core-js/blob/master/tests/tests/es.map.js

**Comment by parro-it** [comment]
> not sure I want to complete/test/publish this :sweat_smile:

You should, it's a nice data structure :+1: 

> almost too flexible, .get([target]) would return Map([selector, promise]), which is not too bad IMHO

I like this, seems a sort of partial apply on the data!

**Comment by bfred-it** [comment]
The correct representation of the data would be this, though:

<img width="517" alt="screen shot" src="https://user-images.githubusercontent.com/1402241/33632544-e5b6f1a6-da48-11e7-95ef-3ea4d894b6ae.png">

The problem is matching a new `['a', 1]` to the existing `['a', 1]`. This might require either searching (expensive `get`/`has`) or an internal MultiMap (as demoed) for the flat map (as screenshotted)

**Comment by sindresorhus** [comment]
Fun fact: `URLSearchParams` is a kind of a multimap. [[1]](https://github.com/whatwg/url/issues/163)

**Comment by reyronald** [comment]
What about other languages? Does anybody know of a language that has such a data structure implemented natively in their API or at least in a library?

We could check the bahvior there and get some inspiration from it

**Comment by bfred-it** [comment]
Here's what I'm talking about in my previous comment: https://runkit.com/bfred-it/multimap-demo/4.0.0

- a Hierarchy index to find the key from a list of keys
- an (almost-)regular Map to store the values with multiple keys

<img width="251" alt="hierarchy index multimap" src="https://user-images.githubusercontent.com/1402241/33652853-dbd8cc7e-daa5-11e7-8eb3-acee9719177c.png">

**Comment by parro-it** [comment]
@bfred-it: you can also create a hash for each object key received,
use an internal map to keep track of them, and use a concatenation of the hashes for multiple keys...

I'll try to write an example to better explain the concept..

**Comment by bfred-it** [comment]
Hashes won't work with Objects, sadly. So `.set({}, {}, 2)` doesn't work as expected.

**Comment by bfred-it** [comment]
Demo with objects: https://runkit.com/bfred-it/5a27b4318dbd6100126bb61c

**Comment by parro-it** [comment]
> Hashes won't work with Objects, sadly. So .set({}, {}, 2) doesn't work as expected.
Sorry, I said `hashes`, but you can use a progression of integers, no need to calculate them based . on object contents...

**Comment by parro-it** [comment]
I mean something like this: https://runkit.com/parro-it/5a27b49a6eda740011659869

**Comment by bfred-it** [comment]
Not bad, it avoids the hierarchical index. It can probably be adjusted so the Map actually looks like this 

<img width="145" alt="user indexes" src="https://user-images.githubusercontent.com/1402241/33654358-cd22e232-daaa-11e7-9b01-560de5976edc.png">


rather than this

<img width="159" alt="anonymous indexes" src="https://user-images.githubusercontent.com/1402241/33654352-c483605c-daaa-11e7-93ba-5efeeee589df.png">

**Comment by parro-it** [comment]
Uhm... seems difficult... how are you thinking to implement that? 
Anyway the keys can be composed in a better way, I agree that joining with \0 produce ugly debug output...

**Comment by bfred-it** [comment]
By thinking like a madman: https://runkit.com/bfred-it/5a27ba9e0d1d6d0012cd859f 😈  (i.e. having a map for the keys)

**Comment by parro-it** [comment]
Ah nice, really smart!

**Comment by parro-it** [comment]
Probably not worth the additional memory consuption, but you'll get very nice logs!

**Comment by bfred-it** [comment]
Yeah, it needs to be seen how it performs compared to your version and to the hierarchical index one.

**Comment by parro-it** [comment]
And you also have to pay attention to avoid memory leaks: 
when you remove items, you should remove their keys from internal maps too (it's difficult because the same object key may appear in diffferent pairs.)

Maybe it's better to use WeakMap to store keys?

**Comment by bfred-it** [comment]
I thought about WeakMap but that wouldn't work for strings and numbers.

**Comment by bfred-it** [comment]
Someone did it:

- same API as my Demo 2: https://github.com/esco/superhash-node
- same concept as URLSearchParam: https://github.com/villadora/multi-map

**Comment by parro-it** [comment]
> That wouldn't work for strings and numbers.

For these, you don't have to store them in key Map: just use them directly as keys...

> Someone did it:

It seems they all calculate an hash based on key content and use that as key...

_Probably_ it's slowly than my idea of progressive ids, but they avoid to internally store every object key (so, they avoid the leak problem I was speaking before)

**Comment by bfred-it** [comment]
I tried them:

* none is iterable
* multikeymap doesn't support objects: https://runkit.com/bfred-it/5a28ffd65db83e0012fe9fbb
* TupleMap works with progressive IDs https://runkit.com/bfred-it/5a28fff6f975b60012d38e2b
* superhash works but uses hashes https://runkit.com/bfred-it/5a29015d57c16c001186d8ee

TupleMap looks like it's the closest one to possibly build on.

**Comment by samchon** [comment]
Visit my project, then you can use the multi-key map.

  - https://github.com/samchon/tstl

**Comment by parro-it** [comment]
@samchon: nice project! You port the whole STL to typescript or only a . subpart?

**Comment by samchon** [comment]
@parro-it Not whole, but most. You visit my project and read the `README`, then you may understand which features are implemented, and which are not. Some features unable to implement (like `thread`) are not implemented. Some features are detoured (`mutex`, `condition_variable`, `vector_bool`, ...).

**Comment by bfred-it** [comment]
It's here, and it's not pretty: https://github.com/bfred-it/multi-key-map

But it works and it's tested! Have a look and feel free to open PRs to add more tests (even if they pass right away)

**Comment by dy** [comment]
There's a couple more: [multikey](https://www.npmjs.com/package/multikey), [multikey-map](https://www.npmjs.com/package/multikey-map).

But - that can be nicely solved with tuples, eg. [immutable-tuple](https://www.npmjs.com/package/immutable-tuple):
```js
import t from 'immutable-tuple'
let map = new WeakMap

let obj = {}
map.has(t(obj, 1)) // false
map.set(t(obj, 1), true)
map.get(t(obj, 1)) // true
```
`immutable-tuple` is a bit bigger (1kb vs 755b `many-keys-weakmap`), but the benefit is ability to use primitive indices as key components.

**Comment by fregante** [comment]
> There's a couple more: [multikey](https://www.npmjs.com/package/multikey), [multikey-map](https://www.npmjs.com/package/multikey-map).

Neither one of them is a real Iterable/Map, which is why I published my own :D
