### ISSUE TITLE
VS Code extension to highlight unused code

### ISSUE THREAD

**Issue by axetroy** [sindresorhus/module-requests#109]
Like it say.

The VS Code's official team seem got no plan to implement this feature.

even they have received a lot of request.

Anyone can write a plugin?

**Comment by sindresorhus** [comment]
Highlight how? Syntax highlight or indicate unused code some other way?

**Comment by axetroy** [comment]
I think ``Syntax highlight`` is a better way. 

Like ``Webstorm``， It make unused variables/import become gray.

Can use babe to do the AST parser job, Analyze the code witch never used, and make it highlight

**Comment by axetroy** [comment]
highlight unused variable/import have been 

This proposal has been proposed for years

Until now official team didn't implement this and no one develop a extension.

**Comment by axetroy** [comment]
![1](https://user-images.githubusercontent.com/9758711/37051417-536bb4fc-21b1-11e8-96aa-efcb67dffe22.png)

Here is the Webstorm highlight

**Comment by parro-it** [comment]
I would love to have this on sublime too.
@sindresorhus do you think it could be implemented as an eslint rule for xo?

**Comment by sindresorhus** [comment]
@parro-it It already is => https://eslint.org/docs/rules/no-unused-vars

**Comment by parro-it** [comment]
> @parro-it It already is => https://eslint.org/docs/rules/no-unused-vars

Oh I never notice it. 
Then @axetroy what is the advantage of having this check as a separate plugin? Couldn't you just use xo or eslint?
