### ISSUE TITLE
which-hosts

### ISSUE THREAD

**Issue by dylang** [sindresorhus/module-requests#12]
### Problem

Where's the `hosts` file? Most put it in `/etc/hosts`, Windows is of course different, and I'm not sure where else it could be.

**Comment by hemanth** [comment]
```js
exports.HOSTS = process.platform === 'win32'
  ? 'C:/Windows/System32/drivers/etc/hosts'
  : '/etc/hosts'
```

**Comment by forivall** [comment]
You should probably use `process.env["SystemRoot"]` instead of hardcoded `"C:/Windows"`. :wink:

**Comment by kevva** [comment]
I made https://github.com/kevva/hosts-path.

**Comment by hemanth** [comment]
I was planning for that, thanks @kevva :+1:
