### ISSUE TITLE
Crontab parser + "next run" feature (Completed ✅)

### ISSUE THREAD

**Issue by fregante** [sindresorhus/module-requests#126]
https://en.wikipedia.org/wiki/Cron#CRON_expression

Like it appears on [https://crontab.guru/#59_1-5_\*/5\_*_1](https://crontab.guru/#59_1-5_*/5_*_1)

```js
parseCron('59 1-5 */5 * 1')

// Would return:
{
  minutes: [59],
  hours: [1, 2, 3, 4, 5],
  days: [5, 10, 15, 20, 25, 30],
  months [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
  weekDays: [1] // Limited to Mondays
}
```

```js
parseCron.nextDate('59 1-5 */5 * 1')
// Would return:
new Date('2020-10-26 01:59:00 GMT')
```

Currently the smallest module available is 500KB https://bundlephobia.com/result?p=recron@1.0.3
But I'm confident that the parser part is not that large.

**Comment by notlmn** [comment]
``` js
const s = '23 0-20/2 */3 1,3-10/2 4/3,1';

const replacements = ['0-59', '0-23', '1-31', '1-12', '0-6'];

function expandRange(range) {
    const [start, end = start + 1] = range.split('-').map(Number);
    return Array.from({length: end - start}).map((val, index) => index + start);
}

function handleDivide(string) {
    const [range, divider = 1] = string.split('/');
    return expandRange(range).filter((item, index) => index % divider === 0);
}

let parts = s.split(' ').map((part, index) => {
    return Array.from(new Set(part.replace('*', replacements[index]).split(',').flatMap(handleDivide)))
});

const cron = {
    minutes: parts[0], // [23]
    hours: parts[1], // [0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
    days: parts[2], // [1, 4, 7, 10, 13, 16, 19, 22, 25, 28]
    months: parts[3], // [1, 3, 5, 7, 9]
    weekDays: parts[4], // [4, 1]
};


```

There you go, a rough parser, just needs other sugary stuff like timezones, days of a month, and everything related to dates 😁

**Comment by fregante** [comment]
Timezones aren’t part of cronjobs, so it’s all good

**Comment by cheap-glitch** [comment]
I wrote [a little module](https://github.com/cheap-glitch/mi-cron/blob/main/index.ts) (<150 lines of TS, 3.5kb JS file un-minified & uncompressed -- this could probably be further diminished).

I tried to follow the proposed API as closely as possible. It can parse standard cron expressions + steps and `@`-shorthands (e.g. `@weekly`). Returns `null` when encountering an invalid expression.

It can also give the next scheduled date (still needs some more testing + support for the week day).

**Comment by fregante** [comment]
That was fast! I wonder if @notlmn’s code could be merged to shorten it further.

I think it's good enough for this feature to exist now 🍰

**Comment by cheap-glitch** [comment]
> That was fast! I wonder if @notlmn’s code could be merged to shorten it further.

It is undeniably much more ingenuous and short, but I'm pretty sure it'll blow up even on slightly incorrect expressions 😄

I made the choice of having a bit more verbosity to be able to check common errors and invalid expressions.

**Comment by fregante** [comment]
Did you reverse-engineer the zip I had posted or is it brand new?

**Comment by cheap-glitch** [comment]
> Did you reverse-engineer the zip I had posted or is it brand new?

I stole a few things from it but mostly it's new.

**Comment by notlmn** [comment]
> It is undeniably much more ingenuous and short, but I'm pretty sure it'll blow up even on slightly incorrect expressions 😄

Yes it would 🤣
