### ISSUE TITLE
lookup-domain-in-hosts-file

### ISSUE THREAD

**Issue by dylang** [sindresorhus/module-requests#13]
### Problem

Sometimes you want to know if a hostname has been mapped in the system's `hosts` file.

### Solution

Something like

```js
hostsLookup('crazy-cat', function(err, ip) { 
  // => ip is false if not found.
  // => ip is value from `hosts` if found.
});
```

**Comment by hemanth** [comment]
@dylang [hosts-lookup](https://www.npmjs.com/package/hosts-lookup) helps?

**Comment by dylang** [comment]
Wow @hemanth, nice work! Looking forward to trying it, I'll let you how it works out.

**Comment by hemanth** [comment]
Thanks :+1:
