### ISSUE TITLE
TypeScript build tool that maps `require('mymodule/foo')` into './src/foo.ts'

### ISSUE THREAD

**Issue by papb** [sindresorhus/module-requests#130]
Rewording the request by @lifeiscontent [here](https://github.com/sindresorhus/awesome-nodejs/discussions/1093#discussioncomment-294710):

Consider the following TypeScript project that will be distributed as a npm package:

```
.
├── package.json
├── src
│   ├── index.ts
│   └── utils.ts
├── tsconfig.json
└── yarn.lock
```

Compiling this will generate `./dist/index.js` and `./dist/utils.js`. To import the module, `require('the-module')` works as long as the `main` field of `package.json` is setup correctly, which is fine and very common to do. However, there is no good way to also provide `./utils.ts` directly as `require('the-module/utils')`. Instead, people would have to do `require('the-module/dist/utils')` which is ugly.

There could be a command line utility to be called within `prepack` that:

* Reorders everything in a way that automatically puts everything available there directly; or
* (hackier) Injects a smart call to [`pirates`](https://www.npmjs.com/package/pirates) on the `index.js` file.

Thoughts?

**Comment by Richienb** [comment]
This can be done in the `resolveId` part of a `rollup` plugin.

**Comment by papb** [comment]
Hi @Richienb, thanks for the fast response!! I may look into it later. @lifeiscontent, what do you think?

**Comment by lifeiscontent** [comment]
@Richienb I'd love to see an example, its hard to visualize as I don't have a full understanding of the ecosystem of rollup.

**Comment by Richienb** [comment]
The `resolveId` function in a rollup plugin is provided with the exact path within an import statement and the file that is importing it as arguments. We can use those arguments to generate a new path to be imported from.

**Comment by Richienb** [comment]
https://github.com/rollup/rollup/issues/558

**Comment by sindresorhus** [comment]
You can solve this with the [`exports` field](https://nodejs.org/api/packages.html#packages_subpath_exports) in package.json, which is the modern way to expose subpaths.

**Comment by lifeiscontent** [comment]
@sindresorhus is this functionality that will work out of the box right now? or something that could be implemented in rollup as a potential feature?

**Comment by sindresorhus** [comment]
There's no need to use Rollup at all.

**Comment by Richienb** [comment]
Ohhhh, I misunderstood the question. I thought you wanted to remap imports from within the module itself on build time, like this rejected TypeScript request: https://github.com/microsoft/TypeScript/issues/15479.

**Comment by papb** [comment]
Ahhh!! Awesome! Thank you all very much!!

@Richienb I was lucky that you misunderstood, because that TS issue you just linked happened to help me with something else here 😅
