### ISSUE TITLE
Batched function calls (debounce) (💚 completed)

### ISSUE THREAD

**Issue by fregante** [sindresorhus/module-requests#136]
Batched execution:

1. `fun(1)`
2. `fun(2)`
3. `fun(4)`
4. Then the original _fun is called as `_fun([1, 2, 4])`

Would be cool:
- original function accepts array
- batched function accepts single item
- option to call batched functions in the next tick or after a timeout (probably defaulting to setTimeout(0) is good enough)

Some of the complexity here is in managing the types for these functions.

Real-life scenario: https://github.com/refined-github/refined-github/pull/5991#discussion_r973028760

**Comment by Richienb** [comment]
```js
function batchFn(function_) {
  let queue = [];

  return function addToQueue(value) {
    queue.push(value);

    if (queue.length === 1) {
      setTimeout(() => {
        function_(queue);
        queue = [];
      });
    }
  }
}
```

**Comment by Richienb** [comment]
Also consider: [`queueMicrotask()`](https://developer.mozilla.org/en-US/docs/Web/API/queueMicrotask)

**Comment by fregante** [comment]
Pretty good! That format also allows to include a simple "ms" parameter to batchFn to pass it straight to setTimeout. 

Types are probably the next difficult part

**Comment by Richienb** [comment]
```ts
export default function batchFn<ValueType>(function_: (value: ValueType[]) => unknown): (value: ValueType) => void;
```

**Comment by fregante** [comment]
Are you going to publish that? 🙏

**Comment by Richienb** [comment]
ok https://github.com/Richienb/batched-function

@fregante would you mind if I added you as a collaborator?

**Comment by fregante** [comment]
Sure. I'd probably like optionally replacing the setTimeout too, like with setImmediate or nextTick

**Comment by Richienb** [comment]
> Sure. I'd probably like optionally replacing the setTimeout too, like with setImmediate or nextTick

I added an option that allows the milliseconds between invokations to be changed, maybe another function could be used when no value is provided but it couldn't be either of those 2 because neither work in the browser.

**Comment by fregante** [comment]
What I wanted was `Promise.resolved().then()` to attempt calling them "synchronously" before the browser paints something on the screen. I think automatically switching to that when the timeout is 0 is a good compromise.

**Comment by Richienb** [comment]
Perhaps it should be used if the timeout is `undefined`, and `setTimeout` is used when timeout is any number.

**Comment by fregante** [comment]
SGTM. Also PR welcome to Refined GitHub to replace the local copy.
