### ISSUE TITLE
Plumbing module

### ISSUE THREAD

**Issue by hemanth** [sindresorhus/module-requests#16]
Function signature: 

```js
plub(<filePath>,<porcessingFunc>,<callBack>)
```

It would be something like:

```js
module.exports = function(path, process, cb) {
  fs.createReadStream(path).pipe(split()).pipe(process).pipe(cb);
}
```

`cb` would receive `err,data` and `data` would be whatever `process` returns, say an `Array` for example.

**Comment by sindresorhus** [comment]
Why? What problem does it solve?

**Comment by hemanth** [comment]
`HugeFile` -> `Processor` -> `Array` 

Say for something like [this](https://gist.github.com/hemanth/7f27a7bc07fa490eea31)

**Comment by sindresorhus** [comment]
So you're looking for something to specifically process lines in a file efficiently without having to deal with streams? What should the return value be, I assume a string of the processed content?

**Comment by hemanth** [comment]
Return value will be whatever the `processor` function returns, it might be `String`, `Array`, `Buffer`, `Stream` whatever.

**Comment by kevva** [comment]
This is somewhat what you want I guess https://github.com/kevva/process-file?

**Comment by hemanth** [comment]
Almost, but instead of:

```js
processFile(file, stream, callback)
```

It should have been:

```js
processFile(file, anyFunc, callback)
```

`anyFunc` would process the lines in the file and return whatever it wishes.

**Comment by forivall** [comment]
that change wouldn't be too hard, it's just 
```
function processFile(file, stream, callback) {
  if (typeof stream === "function") {
    stream = require("through2")(stream);
  }
  ...
}
```

**Comment by hemanth** [comment]
Tired the below with the above change, and noticed an error, missing something?

```js
process = require('./index.js');

var massageItem = function(line){
	// R.E from feross/hostile
    var matches = /^\s*?([^#]+?)\s+([^#]+?)$/.exec(line);
	console.log(matches);
    if (matches && matches.length === 3) {
        //console.log('found');
		var hostMap = {};
        hostMap[matches[2]] = matches[1]; // host:ip
        return hostMap;
    }
};

process('/etc/hosts',massageItem, function(err,data){
	console.log(err,data)
})
```

```sh
_stream_readable.js:716
    process.nextTick(function() {
            ^
TypeError: undefined is not a function
    at resume (_stream_readable.js:716:13)
    at ReadStream.Readable.resume (_stream_readable.js:708:5)
    at ReadStream.Readable.on (_stream_readable.js:676:10)
    at ReadStream.Readable.pipe (_stream_readable.js:537:7)
    at module.exports (/private/tmp/process-file/index.js:30:8)
    at Object.<anonymous> (/private/tmp/process-file/l.js:15:22)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

And with:

```js
process('/etc/hosts',massageItem(), function(err,data){
	console.log(err,data)
})
```

```sh
console.js:29
    throw new TypeError('Console expects a writable stream instance');
          ^
TypeError: Console expects a writable stream instance
    at new Console (console.js:29:11)
    at console.js:111:18
    at NativeModule.compile (node.js:805:5)
    at Function.NativeModule.require (node.js:774:18)
    at node.js:214:27
    at massageItem (/private/tmp/process-file/l.js:6:2)
    at Object.<anonymous> (/private/tmp/process-file/l.js:15:22)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```

**Comment by forivall** [comment]
does `process('/etc/hosts', require('through2')(massageItem), function (err, data) { ... ` work, without the above change?

**Comment by hemanth** [comment]
Well, it's the same:

```js
_stream_readable.js:716
    process.nextTick(function() {
```

**Comment by forivall** [comment]
My bad, in haste, I didn't read the `through2` docs properly. Use ``through2-map`` instead of `'through2'`.

**Comment by hemanth** [comment]
Same :cry:

**Comment by kevva** [comment]
> processFile(file, anyFunc, callback)

Well, then it isn't real streams, so why bother?

**Comment by hemanth** [comment]
`myFunc` may be a stream or not, that must be taken care in `processFile` ?

**Comment by kevva** [comment]
You could just throw in a `through` module/function in there.

**Comment by hemanth** [comment]
@kevva Tired [this](https://github.com/sindresorhus/module-requests/issues/16#issuecomment-124818206)

**Comment by forivall** [comment]
@hemanth so, did through2-map work?

**Comment by hemanth** [comment]
Same results @forivall : 

```sh
_stream_readable.js:716
    process.nextTick(function() {
            ^
TypeError: undefined is not a function
```

**Comment by forivall** [comment]
rename your `process` function to `processFile`. This is why you require things instead of copy and pasting.

**Comment by forivall** [comment]
tada: https://gist.github.com/forivall/0714eb52ccd0107e754e
If you really care, I'll package this up into a module, since one require statement's probably easier than 4.

**Comment by hemanth** [comment]
Duh `process` :cactus: I was so much engrossed in the stream part of it, it's a part of [host-lookup](https://github.com/hemanth/hosts-lookup)

It would be nice, if we could add this feature to https://github.com/kevva/process-file.
