### ISSUE TITLE
Launch executable at login / startup for Linux

### ISSUE THREAD

**Issue by adam-lynch** [sindresorhus/module-requests#17]
Like https://github.com/Teamwork/node-auto-launch but for Linux. We (@Teamwork) created this but haven't a clue how to do it for Linux. It's not a high priority for us right now but would be nice. We use the module already for NW.js. You might find this useful for Electron or might know of an alternative that covers the use case.

**Comment by forivall** [comment]
The starting point for this would be to read the [Freedesktop Autostart Specification](http://standards.freedesktop.org/autostart-spec/autostart-spec-latest.html). -- TL;DR: Create a `.desktop` file in `$HOME/.config/autostart`; to disable entries, set `Hidden=true` or delete the `.desktop` file

However, it's very likely that there will be different quirks for different desktop environments, and fallbacks like `~/.xsession`, etc. You will definitely need to set some guidelines around what kind of bugs will and won't be fixed.

**Comment by adam-lynch** [comment]
@forivall thanks for the heads start :+1:

**Comment by squarejaw** [comment]
https://github.com/typicode/user-startup appears to work in OS X, Linux and Windows.

**Comment by adam-lynch** [comment]
Linux support added thanks to help from @willbarrett; see https://github.com/Teamwork/node-auto-launch. 10/10 would recommend module-requests :stuck_out_tongue:
