### ISSUE TITLE
time-at

### ISSUE THREAD

**Issue by hemanth** [sindresorhus/module-requests#18]
I always had this in my todo list:

```
timeat UTC 
```

```
timeat newyork
```

```
timeat UTC+5.30
```

```
timeat [TZ] [city] [country]
```

**Comment by sindresorhus** [comment]
@substack did a module for this some time ago: https://github.com/substack/tzloc

**Comment by hemanth** [comment]
@sindresorhus Nice, expect it needs [issues#2](https://github.com/substack/tzloc/issues/2) to be fixed, PR is pending.
