### ISSUE TITLE
Module to check if an integer is narcissistic

### ISSUE THREAD

**Issue by robbbz** [sindresorhus/module-requests#20]
Should just return a boolean to check if a number is narcissistic<sup>1</sup>. I tried it but it's harder than you would think.

-

<sup>1</sup> https://en.wikipedia.org/wiki/Narcissistic_number:

> In recreational number theory, a narcissistic number (also known as a pluperfect digital invariant (PPDI), an Armstrong number (after Michael F. Armstrong) or a plus perfect number) is a number that is the sum of its own digits each raised to the power of the number of digits. This definition depends on the base b of the number system used, e.g., b = 10 for the decimal system or b = 2 for the binary system.

**Comment by gillstrom** [comment]
Could [is-narcissistic](https://github.com/gillstrom/is-narcissistic) work out for you?

**Comment by gillstrom** [comment]
Oh.. bases..

**Comment by kevva** [comment]
https://github.com/gillstrom/is-narcissistic

**Comment by robbbz** [comment]
thanks! Great!
