### ISSUE TITLE
Human-input date parsing module for English

### ISSUE THREAD

**Issue by dthree** [sindresorhus/module-requests#22]
See this post:

http://stackoverflow.com/questions/31949090/js-standalone-user-input-date-interpreter

I can't find any Node module that simply parses user-input dates and outputs a standard JS date object. This could be super compact and ridiculously useful.

**Comment by forivall** [comment]
I did a quick search and found https://github.com/substack/parse-messy-time . Of course substack made it :stuck_out_tongue:

**Comment by dthree** [comment]
sweet - for some reason I hadn't seen that! Thanks.
