### ISSUE TITLE
[CLI] Speedtest.net

### ISSUE THREAD

**Issue by Whoaa512** [sindresorhus/module-requests#23]
Not sure if they have an API, or if it could be done without http://speedtest.net, but I would love for this to exist if it doesn't already.

**Comment by sindresorhus** [comment]
Here you go: https://github.com/sindresorhus/speed-test

**Comment by Andersos** [comment]
What about this https://github.com/tkh44/node-speedtest-cli

**Comment by sindresorhus** [comment]
@Andersos It's says so right in the description why you wouldn't want that one:

> Node **wrapper for the python package** speedtest-cli
