### ISSUE TITLE
ESLint rule plugin - Prevent use of extended native object

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/module-requests#25]
[Proposed](https://github.com/eslint/eslint/issues/3426) the rule on ESLint, but they weren't interested. I would really like to have it, but I don't have the time right now to implement it. Any takers? Happy to discuss.

[ESLint docs on creating a plugin.](http://eslint.org/docs/developer-guide/working-with-plugins)

The [`no-extend-native`](https://github.com/eslint/eslint/blob/master/lib/rules/no-extend-native.js) rule might be useful as inspiration.

---

## ESLint ticket

Similar to [`no-extend-native`](http://eslint.org/docs/rules/no-extend-native), but the intention of this is to prevent usage of extended native objects, not creation.

When using external Node modules you can't control whether they extend native objects. I would still like to prevent usage of it. When the type can be detected it should check whether the property/method is a known native one, and if not, throw a violation.

A good example is the [colors](https://github.com/marak/colors.js/) module which extends the string prototype with [coloring setter properties](https://github.com/Marak/colors.js/blob/90dd85b173cc48d668412a84306bf6b01751dd21/lib/extendStringPrototype.js).

This should be a violation as there's is no `green` property on the native string prototype:

```js
var colors = require('colors');
console.log('unicorn'.green);
```

-

I've made a [module](https://github.com/sindresorhus/proto-props) with a static list of prototype properties for each type, which could potentially be used.

**Comment by IanVS** [comment]
If nobody else jumps in, I can try taking a crack at it later this week.  Should be pretty straight-forward I think.

**Comment by dustinspecker** [comment]
Published an initial starting point: https://github.com/dustinspecker/eslint-plugin-no-use-extend-native.

In the future, I want to look into seeing if we can be smarter and look at variable declarations to determine a type. Right now, the plugin just looks at literals and new expressions.

**Comment by sindresorhus** [comment]
@dustinspecker Awesome! That was fast.

> In the future, I want to look into seeing if we can be smarter and look at variable declarations to determine a type. Right now, the plugin just looks at literals and new expressions.

Can you open an issue on your repo to track that? Maybe expand on the description a bit in the issue in case anyone else wants to help out.

-

@IanVS Would be cool if you could review it.

-

I'll keep this issue open for a while for discovery in case anyone wants to help out improve it.

**Comment by IanVS** [comment]
@dustinspecker @sindresorhus Looks awesome to me!
