### ISSUE TITLE
Chalk extension - line break colored strings

### ISSUE THREAD

**Issue by dthree** [sindresorhus/module-requests#28]
I was trying to write a quick function for this and it's proving harder than I thought, requiring a tricky algorithm.

Suppose you have the following string:

    var str = chalk.green('Hello Sindre. This is trickier than I thought.');

You want a line break function, which would do this:

    var lines = break(str, 20);

Ideally it would split on the closest word break to 20 lines per row. So this would return:

    Hello Sindre. This \n
    is trickier than I \n
    thought.

That's easy. Now introduce color characters:

1. If you split the line mid a color, you don't properly end off that color code, and the next line will be the default color.

2. When determining line lengths on where to split each line, the colors throw off the line lenght, so you have to do some sort of binary search recursive function to determine the visible length vs. the actual length.

---

### Why do we care?

If you want to do fancy terminal styles with colors, such as columns, or padding all content right two lines, you need to be able to programmatically handle line wraps.

A line wrap function would be invaluable!

Anyway, I haven't had the time to make anything workable yet, so if anyone else wants to pick it up, I'd definitely use it.

**Comment by dthree** [comment]
NVM, got it over with and managed to make it fairly compact. @sindresorhus if you want to make this a module under your name, go ahead. It's a lot more likely to be used by ppl in that case.

This meets all of my above requirements.

```js

const colors = ["\\u001b[0m", "\\u001b[1m", "\\u001b[2m", "\\u001b[3m", "\\u001b[4m", "\\u001b[5m", "\\u001b[6m", "\\u001b[7m", "\\u001b[8m", "\\u001b[30m", "\\u001b[31m", "\\u001b[32m", "\\u001b[33m", "\\u001b[34m", "\\u001b[35m", "\\u001b[36m", "\\u001b[37m", "\\u001b[39m", "\\u001b[40m", "\\u001b[41m", "\\u001b[42m", "\\u001b[43m", "\\u001b[44m", "\\u001b[45m", "\\u001b[46m", "\\u001b[47m"];
const util = require('util');
function wrap(string, width) {
  let text = util.inspect(string);
  text = text.slice(1, text.length -1);
  let color = void 0;
  let lines = [];
  let line = '';
  let lineN = 0;
  let fullN = 0;
  let stripped = chalk.stripColor(string);
  function endLine() {
    if (color) {
      line += color;
    }
    lines.push(line);
    line = '';
    lineN = 0;
  }
  function nextSpace(str) {
    let ctr = 0;
    str = chalk.stripColor(str);
    for (var i = 0; i < str.length; ++i) {
      if (str[i] === ' ') {
        return ctr;
      } else {
        ctr++;
      }
    }
    return void 0;
  }
  for (let i = 0; i < text.length; ++i) {
    let spaceN = nextSpace(stripped.slice(fullN)) || 0;
    if ((lineN + spaceN + 2) >= width) {
      endLine();
    }
    let char = text.slice(i, i + 1);
    let nChars = text.slice(i, i + 10);
    let nMatch = (colors.indexOf(nChars) > -1) ? nChars : void 0;
    if (nMatch === undefined) {
      line += char;
      lineN++;
      fullN++;
    } else {
      color = (nMatch === '\\u001b[39m') ? void 0 : nMatch;
      line += nChars;
      i += 9;
    }
  }
  endLine();
  return String(lines.join('\n')).replace(/\\u001b/g, '\u001b');
}

const str = 
  'The quick brown ' + 
  chalk.red('fox jumped over ') + 
  'the lazy ' + 
  chalk.green('dog and then ran ' + 
    'away with the unicorn.');

console.log(wrap(str, 40));

```

**Comment by bucaran** [comment]
> Ideally it would split on the closest word break to 20 lines per row.

You mean 20 columns per row.

You can do this with [clor](https://github.com/bucaran/clor).

Example:

```js
require("./")("Hello Sindre. This is trickier than I thought.").break(20)
require("./").blue("Hello Sindre.")._.red("This is trickier")._.green("than I thought.").break(20)
require("./")("Hello Sindre.")._.red("This is trickier")._.green("than I thought.").break(20)
```

![clor](https://cloud.githubusercontent.com/assets/8317250/9350868/3c596502-468f-11e5-87ec-69da2348cdc2.png)

**Comment by bucaran** [comment]
```js
require("./").red('The quick brown ')('the lazy ').green('dog and then ran away with the unicorn.').break(40)
```

**Comment by dthree** [comment]
Sweet. This is why I don't write algorithms.

No, hadn't heard of clor. Looks like you did a pretty good job.

I do think that it would fit well as its own module, though.

**Comment by dthree** [comment]
@bucaran ah snap. Your function was impressively smaller so I checked it out, and it's just missing one little thing.

You don't terminate colors on each line if it wraps to the next, so if you try to do something fancy like columns, you can't do this:

```js
 whitecol   greencol
 whitecol   greencol
 whitecol   greencol
 whitecol   greencol
 whitecol   greencol
```

See this example (brk is your function, made independent of clor):

```js
let splits = brk(str, 20);
let lines = String(splits).split('\n');
for (let i = 0; i < lines.length; ++i) {
  lines[i] = '  previous column  ' + lines[i];
}
let result = lines.join('\n');
```

In this instance, 'previous column' gets turned red and green in some instances. This can be handled by doing a color end tag at the end of each line break, and then restarting up that same color at the beginning of the next line. That's what most of the complexity on my fn was doing.

Maybe you could amend clor with this fix?

**Comment by sindresorhus** [comment]
I did a module in the chalk org inspired by @bucaran code, but with wrapping on words, not on characters: https://github.com/chalk/wrap-ansi

-

@dthree Would love a review and possible improvements :)

**Comment by sindresorhus** [comment]
@Qix- @jbnicolai fyi

**Comment by dthree** [comment]
@sindresorhus sweet - looks good. If we just sort out this column thing I was talking about (my code does it, I'll try and get a moment to implement it in yours), I'll definitely depend on it for my upcoming repo `wat`, which is probably going to be pretty huge once I release it :)

https://github.com/dthree/wat

**Comment by bucaran** [comment]
@dthree I see, I see :sweat_smile: 

@sindresorhus Has `wrap-ansi` already fixed this?

**Comment by dthree** [comment]
@bucaran no, it hasn't yet.

I'm willing to do a PR to fix, I just haven't gotten to it yet. But you kind of get what I'm talking about and why this would be useful?

**Comment by bucaran** [comment]
@dthree Sure. What code to generate the failing example using `clor` or `chalk`?

**Comment by bucaran** [comment]
So, maybe in your example, it would be easier to do something like the following instead?

```js
const clor = require("clor")
const data = [0,0,0,0,0].map(function (o) { return { left: "whitecol", right: "greencol" } })
data.forEach(function (item) { clor(item.left).tab.green(item.right).log() }) 
```

**Comment by dthree** [comment]
This should do it (if clor returns the string)

```js

var str = clor('The quick brown ')
  .red('fox jumped over ')('the lazy ')
  .green('dog and then ran away with the unicorn.')
  .break(40);

let lines = String(str).split('\n');
for (let i = 0; i < lines.length; ++i) {
  lines[i] = '  previous column  ' + lines[i];
}
let result = lines.join('\n');

console.log(result);
```

**Comment by bucaran** [comment]
@dthree I see. You are manipulating the returned string. Perhaps a change in the approach could solve this more easily? What do you think of my example above?

**Comment by dthree** [comment]
On your last, I think the main point is that each line, if starting with a color, should re-initiate that color so as to be separate from the previous line. It's much cleaner.

**Comment by bucaran** [comment]
>  if starting with a color, should re-initiate that color so as to be separate from the previous line. It's much cleaner.

Yes. That sounds like something to fix in `clor`, but the code above does do what you need right?

**Comment by dthree** [comment]
Not totally, because I need to do all kinds of changes and manipulations to these strings, and you example just handles an edge case. It doesn't really address the problem.

**Comment by dthree** [comment]
For example, what is the `greencol` above what a `rainbowcol`?

**Comment by bucaran** [comment]
@dthree Well, first we need to fix that little issue of re-initiating the color on each line. If it does, then you should be able to manipulate the string in the way you desire, right?

> For example, what if the greencol above was a rainbowcol?

`clor` does not have the rainbow prop like [colors.js](https://github.com/marak/colors.js/), but assuming it did the following should work:

```js
console.log(clor(item.left).tab.rainbow(item.right).toString()) 
```

**Comment by dthree** [comment]
Haha - what I'm saying is that you don't know what is in the right column - so you can't manipulate it afterwords.

Like if the right column was like this:

    greenredredr
    edgreenyello
    wgreengree
    nblue

There would be nothing you could do to re-assign the colors later, which is the whole point.

But yes, with that fix done, all problems would be solved :D

Do note that you must:

1. End the color string on line A,
2. Re-initiate it on line B.

Lets make an example with tags to make it simple:

    <red>Hi my name is George</red> and your name <green> is Jack</green>

For 14-wide columns, that would have to become:

    <red>Hi my name is</red>
    <red>George</red> and 
    your name <green> is </green>
    <green>Jack</green>

**Comment by bucaran** [comment]
Gotcha. I'll update `clor` with this bit, and also depend on `wrap-ansi` for the break part, or maybe advice users to depend in it for their word wrapping needs. :smile: 

I have a day of work ahead of me, but I should be able to complete this later tonight. Feel free to [give it a shot](https://github.com/bucaran/clor/blob/master/index.js) if you have some time. 

By _it_, I mean the color issue (end color on line A and reopen on line B...) which should be an easy fix unless I am missing something.

**Comment by sindresorhus** [comment]
@dthree 

> sweet - looks good. If we just sort out this column thing I was talking about (my code does it, I'll try and get a moment to implement it in yours),

You're awesome! :)

> I'll definitely depend on it for my upcoming repo wat, which is probably going to be pretty huge once I release it :)

I tried out `wat`. Really cool idea!

Wish you could execute a search right from the CLI though: `$ wat js array splice`. That just opens an empty `wat` REPL. Would be happy to tweet about it when you feels it's ready enough for public consumption. Just ping me somewhere.

```
$ wat
? chalk
```

:D

You might also want to use [`leven`](https://github.com/sindresorhus/leven) over `levenshtein` as it's 35 times faster.

**Comment by Qix-** [comment]
Definitely +1 for wat. Usually not a fan of documentation utilities but I think it's correct in identifying small API lookups as a serious time waster.

**Comment by dthree** [comment]
@sindresorhus thanks! That's really a a lot to me coming from you.

I'll absolutely be supporting the straight CLI - that was most definitely an intended feature. It'll support every command `wat` supports, and then just exit out when done. The only thing I don't think I know how to do is add support for the autocompletion without opening the app, but then one can always just quickly run it if they want to get fancy.

Didn't see `leven` - sounds much better. I'll be throwing that in there.

**Comment by dthree** [comment]
@Qix- Thanks man! Appreciate it.

**Comment by sindresorhus** [comment]
> The only thing I don't think I know how to do is add support for the autocompletion without opening the app, but then one can always just quickly run it if they want to get fancy.

Don't have to exit right I away. I meant it should open the `wat` repl with the arguments filled out. So `$ wat js splice array` should open the `wat` REPL with `js splice array` filled out and runned.

**Comment by Qix-** [comment]
Why not [Bash auto-completion](http://www.tldp.org/LDP/abs/html/tabexpansion.html)? Without looking at the wat source too much, maybe you could use an autocomplete script to invoke wat with a flag that indicates you want potential matches coming back.

[And for Zsh](http://zsh.sourceforge.net/Doc/Release/Completion-System.html).

**Comment by dthree** [comment]
@sindresorhus will do! :sparkles:

**Comment by dthree** [comment]
@Qix- thanks, I'll check it out. I'd never done Bash auto-completion before, so I imagined it to be more difficult than that and didn't realize you could invoke a program to handle it.

**Comment by sindresorhus** [comment]
Example here: https://github.com/gulpjs/gulp-cli/tree/master/completion

**Comment by Qix-** [comment]
Yeah it's actually not that hard. :+1:

**Comment by dthree** [comment]
:+1: It's officially on the release feature list!

**Comment by bucaran** [comment]
And for [fish](http://fishshell.com/docs/current/commands.html#complete), don't forget fish :sweat:

**Comment by dthree** [comment]
@bucaran haha what do you mean on Fish?

**Comment by dthree** [comment]
@sindresorhus `leven` implemented :rocket:

**Comment by bucaran** [comment]
@dthree Completions for fish as well. I don't use bash or company.

**Comment by dthree** [comment]
ah :)

**Comment by dthree** [comment]
@Qix- I've been looking at all these tabbed completion examples (this is new to me), and it seems each user would need to opt in or manually add something to their `.bashrc` file, etc. etc.

Do you know how to automatically configure it on a node install or if this is possible?

**Comment by Qix-** [comment]
I know it's possible with installing stuff i.e. via `brew` or `apt-get`. I think it's a matter of where they are stored (though don't quote me on it).

**Comment by bucaran** [comment]
Don't know about bash, but in the case of fish, there is the `$fish_complete_path` variable to which you just need to append the path to the completions file or directory. This file is a regular fish file and can run any code. There you use the `complete` command to generate the completions passing things such as the name, key that triggers the completion and even a subshell to create conditional completions (for example git).

**Comment by dthree** [comment]
@sindresorhus  I'll bet you could make some ridiculously useful apps with this framework if you gave it some thought.

https://github.com/dthree/vorpal

If you don't believe me, I'll let you know when I release something else I've got up my sleeve that depends on it, in addition to `wat`, which is also based on Vorpal. But I'd love to see what someone as creative as you could come up with :fire:
