### ISSUE TITLE
url-format-lax

### ISSUE THREAD

**Issue by silverwind** [sindresorhus/module-requests#32]
Something like https://github.com/sindresorhus/url-parse-lax, but for `url.format`:

```js
var format = require('url-format-lax');

format({host: 'google.com', port: '123'}); // => google.com:123
format({host: '::', port: '123'}); // => [::]:123
```

**Comment by sindresorhus** [comment]
I assume this is what you want: https://github.com/sindresorhus/url-format-lax ?

Btw, your second test case already works like that with the builtin `url.format()`.

Any other cases it should handle? Description suggestion?

**Comment by silverwind** [comment]
:+1: works for my use case of formatting logs with `host` and `port`.

One could add support for all URL properties by just callng into `url.format()` and removing the protocol from the output, thought I'm not sure someone is ever going to need `host:port/path`.

As for the the description, I'd use 

> protocol-less url.format()
> Format a hostname and port into IPv6-compatile socket form of `hostname:port`.

**Comment by silverwind** [comment]
I'll PR you a few changes.

**Comment by silverwind** [comment]
Thanks!
