### ISSUE TITLE
ghp-cli

### ISSUE THREAD

**Issue by iamstarkov** [sindresorhus/module-requests#33]
github pages are cool, but there are too few themes there and there is no cli for them, so I want to have some cli tool, which will create html page from repo’s `readme` with data from `package.json` (useful for google analytics). I want to use this tool as postpublish step for building my npm packages to have uptodate pages about them. Publishing them is another story and I’m fine with [buildbranch](https://github.com/nfroidure/buildbranch)

MVP for me is ghp is using `./node_modules/${theme}/index.jade` template and variable `pkg` which is basically repo’s package.json. CSS and JS files can be hosted in the theme’s github page.

```
$ ghp --help

    Usage
      $ ghp <destination-folder>
      
    Options
      --theme=<theme> — ghp theme located in node_modules with template
      
    Example
      $ ghp --theme=ghp-cayman dist
      $ ls dist
      3 index.html
```

I hoped to build this tool on my own, but desperately have no time now. Maybe you or community can take care for this idea and everybody will benefit from it. What do you think about it?

**Comment by sindresorhus** [comment]
You don't have to use the default GitHub Pages themes. You can design your own theme or use external ones. The benefit of Jekyll through GitHub Pages is that your only have to push to `gh-pages` and it just works. No compiling. No setup.

How is `ghp` better? Why would I use it over GitHub Pages?

**Comment by iamstarkov** [comment]
ghp is not better, its sligthly different, sorry for confusing.
maybe better name is just readme-html or smth, ’cause I only want to generate html pages from projects’ readme with some data in it with my templates.

**Comment by iamstarkov** [comment]
found that i can live with simple md files
