### ISSUE TITLE
credits - to see who built the stuff we depend on

### ISSUE THREAD

**Issue by dylang** [sindresorhus/module-requests#36]
*Think `npm ls` meets `IMDB`.*

**Pseudocode**

For all node modules, extract the author, reduce it to some nice format.

**Reasoning**

I'm pretty sure the primary reason I'm productive with node is thanks to the hard work from a relatively small set of individuals. I'd like to see their contributions quantified and the identities of the lesser known individuals to be more discoverable.

**Comment by Qix-** [comment]
Could you give an example of what you think the output would look like? I'm having trouble visualizing what it would display.

**Comment by dylang** [comment]
@Qix- I intentionally didn't specify to see what others would imagine from the description, but maybe my description was too vague. 

If this was a cli tool, then maybe something like this:

```bash
> credits
Sindre Sorhus: Ava, Chalk, Cli-Cursor
TJ Holowaychuk: Commander
```

Consider that quickly thrown together to get the idea across, not what I think the UX needs to look like.

Of course it gets complicated when some projects have `maintainers` in addition to or instead of a single `author` field, but I'm only thinking about the goal: learn about who's making the dependencies we are using, and is it something people are interested in having a module for this purpose.

**Comment by forivall** [comment]
similar in idea to http://makerba.se, but automatically generated from authors and dependencies?

**Comment by sindresorhus** [comment]
Cool idea! Would definitely like to see this exist.

**Comment by stefanjudis** [comment]
Sounds like a nice little project - I'd like to give a shot, if no one started already. ;)

**Comment by sindresorhus** [comment]
@stefanjudis Go for it! :)

**Comment by stefanjudis** [comment]
<img width="1131" alt="screenshot 2015-10-25 14 51 53" src="https://cloud.githubusercontent.com/assets/962099/10715941/f9108618-7b27-11e5-8eac-2e2b9d3e0a66.png">

Almost there. :)

**Comment by sindresorhus** [comment]
Yeah, limit it to 5. Could always have a flag to show all if that's interesting, but the main focus is showing the people, not the packages.

**Comment by stefanjudis** [comment]
Agree - went with this. 

```
const cli = meow(`
  Usage
    $ credits <path>

  Options
    -i, --include-packages  Show packages maintained by person

  Examples
    $ credits /projects/foo
    $ credits /projects/foo --include-packages
`, {
  alias : {
    i : 'includePackages'
  }
} );
```

**Comment by dylang** [comment]
Nice work @stefanjudis! Thanks for building this!

I like how you sorted the authors by package count and package names alphabetically. 

The author's email is interesting. I wonder if it's possible to deduce author's github home page from their package repository url.

Are you looking at top level packages only or recursing down? 

Looking forward to trying it out!

**Comment by stefanjudis** [comment]
@dylang 

Thanks... I'm almost done. Tests are missing. :) 
So maybe I'll get it out today.

> Are you looking at top level packages only or recursing down?

I'm recursing down. :)
But am thinking of making this configurable. Not sure about that yet. :)

**Comment by stefanjudis** [comment]
https://github.com/stefanjudis/credits-cli
https://github.com/stefanjudis/credits

Here we go. Comments welcome. :bowtie:

**Comment by dylang** [comment]
Great work @stefanjudis!

I played with the code using a cli table module, it made the output feel a bit more readable to me, what do you think?

```
AUTHOR                                          COUNT PACKAGES
Sindre Sorhus <sindresorhus@gmail.com>             96 ava, ava-init, arr-exclude, pify, read-pkg-u
John-David Dalton <john.david.dalton@gmail.com>    30 lodash, lodash.clonedeep, lodash._baseclone,
mathias <mathias@qiwi.be>                          28 lodash, regexpu, regenerate, jsesc, lodash.c
phated <blaine@iceddev.com>                        25 lodash, lodash.clonedeep, lodash._baseclone,
kitcambridge <github@kitcambridge.be>              25 lodash, lodash.clonedeep, lodash._baseclone,
d10 <demoneaux@gmail.com>                          25 lodash, regjsgen, lodash.clonedeep, lodash._
isaacs <i@izs.me>                                  21 graceful-fs, slide, minimatch, glob, infligh
Sebastian McKenzie <sebmck@gmail.com>              18 babel-core, babel-plugin-constant-folding, b
James Halliday <mail@substack.net>                 16 mkdirp, minimist, concat-map, wordwrap, reso
Takuto Wada <takuto.wada@gmail.com>                12 babel-plugin-espower, escallmatch, array-for
Jon Schlinkert                                     11 arr-flatten, center-align, align-text, kind-
jonschlinkert <github@sellside.com>                11 arr-flatten, center-align, align-text, kind-
Olov Lassus <olov.lassus@gmail.com>                 9 defs, alter, ast-traverse, breakable, simple
jbnicolai <jappelman@xebia.com>                     9 strip-ansi, ansi-regex, chalk, ansi-styles,
medikoo <medikoo+npm@medikoo.com>                   8 es6-map, d, es5-ext, es6-iterator, es6-set,
othiym23 <ogd@aoaioxxysz.net>                       8 normalize-package-data, hosted-git-info, sem
isaacs <isaacs@npmjs.com>                           8 normalize-package-data, semver, brace-expans
Mariusz Nowak <medyk@medikoo.com>                   8 es6-map, d, es5-ext, es6-iterator, es6-set,
---cut--
```

I'm noticing most of the people have just one package, and that one package is shared across a lot of people, so maybe packages with a lot of contributors could be listed separately, grouped by package name. 

Or maybe this would be insightful by being less overwhelming and only showing top % of contributors by default.

```
...and 230 other contributors. Use --all to see their names too.
```

I wonder why he's listed twice:
```
Jon Schlinkert                                     11 arr-flatten, center-align, align-text, kind-
jonschlinkert <github@sellside.com>                11 arr-flatten, center-align, align-text, kind-
```

**Comment by Qix-** [comment]
Probably because he has it listed weird. Multiple emails or something.

**Comment by sindresorhus** [comment]
Why show email? I would rather show GitHub username.

**Comment by stefanjudis** [comment]
@dylang 

Yeah I played with table options, too. Maybe want to PR something? Totally agree, that the representation could be better.

> I'm noticing most of the people have just one package, and that one package is shared across a lot of people, so maybe packages with a lot of contributors could be listed separately, grouped by package name.

A lot of people have typos in their name fields and/or are changing name/email. That's why a few people show up multiple time. I can not think of a reliable way to avoid that. :(

@sindresorhus 
> Why show email? I would rather show GitHub username.

Hmm, that's information we don't have. If it's only the author who's hosting the project, that's possible, but e.g. for maintainers I don't know it without fetching this information.

I'd love to make everybody who wants to collaborate on that to make him a collaborator on the projects.

Maybe we want to add issues there?

**Comment by sindresorhus** [comment]
> Hmm, that's information we don't have. If it's only the author who's hosting the project, that's possible, but e.g. for maintainers I don't know it without fetching this information.

You have their email, so from that you could potentially get the GitHub username of some of them: https://github.com/sindresorhus/github-username 

And when the GitHub username can't be inferred, show the author website if available.

**Comment by stefanjudis** [comment]
Jap, fetching is an option.

But I'm not sure - if fetching 200 - * usernames ( surely depending on the project )  is the right approach here, tbh.

This slows the process down heavily.

**Comment by sindresorhus** [comment]
Yeah, probably not worth it.

**Comment by stefanjudis** [comment]
@sindresorhus what do you think - can we close this one here?
