### ISSUE TITLE
Gatling runner

### ISSUE THREAD

**Issue by michaelBenin** [sindresorhus/module-requests#4]
Gatling is awesome, would be great to run it with Node.js. 

http://gatling.io/#/

**Comment by sindresorhus** [comment]
Can you add some more info? How is it used? Is there a self-contained binary available? Are you looking for an API or CLI? If API, how would it look?

**Comment by sindresorhus** [comment]
ping @michaelBenin

**Comment by sindresorhus** [comment]
Closing for lack of response from OP.
