### ISSUE TITLE
List files by "meta" type

### ISSUE THREAD

**Issue by danilosampaio** [sindresorhus/module-requests#41]
Given a base directory, lists files by "meta" type, e.g, Image, Archive and compressed, Database, Document, Font, etc.

##### * to make it asynchronous, it could use a event-based file walker
Ex:
```js
var listByType = require('list-by-type');
var walker = listByType.walk('/home/me', {
  'Image': ['jpg','png','gif'],
  'Documents': ['doc','pdf','txt']
});
```
Return: Event-based file walker
```
walker.on('file', function (fileStats) {
//do something: calculate disk usage, list file names by type, etc.
//fileStats.metaType: 'Images', 'Documentos'
});

walker.on('end', function () {
  console.log('Done.')
})
```

A good reference: https://en.wikipedia.org/wiki/List_of_file_formats

**Comment by Qix-** [comment]
This could easily use the [magic file format database](http://www.magicdb.org/magic.db) used by unix' `file` command.

**Comment by danilosampaio** [comment]
@Qix- thanks for helping

I was thinking of something simpler, based only on the extension. Magic number is a good strategy when one wishes to check the actual file type, regardless of the extension, moreover, rapidly comparing the two lists (wikipedia vs magicdb), there is a drastically different in the number of known types.

**Comment by Qix-** [comment]
Well sure, but `file` checks extension as well. I figured that was a given :+1:

**Comment by danilosampaio** [comment]
I just made a module for that ([twalker](https://github.com/danilosampaio/twalker)). Suggestions and feedback are very appreciated.
