### ISSUE TITLE
Aggregate "+1" comments of an issue into one single comment with @mention of +1'ers  

### ISSUE THREAD

**Issue by mohsen1** [sindresorhus/module-requests#42]
This is more like a script but can be wrapped inside a module. The +1 comments on issues are annoying and a lot of people are deleting them. Instead of this we can have a bot that goes through issues one by one and does following:
- If there is no "+1" comment ignore it
- For each "+1" comment
  - look for "all of +1s comment" generated previously 
    - if that comment doesn't exist create one and put @mention of all +1ers in it
    - otherwise edit the comment and add +1ers @mentions to the comment 
  - Delete the +1 comment

Detecting a "+1" comment
A comment is a "+1" comment if:
- only includes one of the following: 
  - "+1"
  - ":+1:"
  - "good idea"
  - "me too"
  - And possibly many more...
- includes one of the list above and one or many emojis like "+1 :smile:"

**Comment by sindresorhus** [comment]
:+1:

**Comment by sindresorhus** [comment]
:+1:

**Comment by sindresorhus** [comment]
+1

**Comment by forivall** [comment]
:clap:

:clap:

:clap:

**Comment by gillstrom** [comment]
I like this

**Comment by mohsen1** [comment]
There is also -1!

**Comment by tuxracer** [comment]
Also: lgtm and :shipit:

**Comment by Qix-** [comment]
Theres a chrome extension for this already.

**Comment by mohsen1** [comment]
Chrome extension does it only for ones who install it. This propose modifying the actual issue comments

**Comment by Qix-** [comment]
Automatic management is asking for problems IMO.

**Comment by stevemao** [comment]
@Qix- can you link the chrome extension?

**Comment by mischah** [comment]
@stevemao
> @Qix- can you link the chrome extension?

https://chrome.google.com/webstore/detail/github-%2B1s/lddfkkebajnpiicnpfamebilmhamkeme?hl=en

**Comment by stevemao** [comment]
Thanks @mischah

**Comment by Qix-** [comment]
Sorry totally thought I responded to this. @mischah got it :+1: Thanks!

**Comment by sindresorhus** [comment]
Closing as we now have comment reactions.
