### ISSUE TITLE
Reduce Node stream into a promise

### ISSUE THREAD

**Issue by RangerMauve** [sindresorhus/module-requests#44]
There's things out there for performing a reduce on a stream taking callbacks along the way, but it'd be nice if there was something out there to use a callback that returns a promise and to have it return a promise for when the stream closes or errors out.

**Comment by sindresorhus** [comment]
Can you link to any of those things?

**Comment by SamVerschueren** [comment]
Maybe I'm not getting your question entirely, but is [get-stream](https://github.com/sindresorhus/get-stream) something you want?

**Comment by forivall** [comment]
or https://github.com/meoguru/node-then-eos / https://github.com/mafintosh/end-of-stream ?

**Comment by RangerMauve** [comment]
@SamVerschueren, @forivall That just gives the end of the stream or concatenates the input. I'd like to perform a reduce operation on the data as it's coming in and the resolve to the result of the reduce. thank you for looking, though.

**Comment by RangerMauve** [comment]
It'd look similar to [promise-reduce](https://github.com/yoshuawuyts/promise-reduce), but with a stream rather than an array being passed in.

**Comment by Ninju** [comment]
I'm not sure if I'm completely misunderstanding, but doesn't something like this do the job?

```
function reduceStream(combine, initialValue, aStream) {
  return new Promise((resolve, reject) => {
    let accumulatedValue = initialValue

    aStream.on('data', (data) => {
      accumulatedValue = combine(accumulatedValue, data)
    })  

    aStream.on('end', () => resolve(accumulatedValue))
    aStream.on('error', () => reject())
  })  
}
```

Is that what you're after?

You'd call it similarly to the "dream API" you wanted, for example:

```
function concat(acc, curr) { return acc + curr; }
reduceStream(concat, '', stream).then(result => console.log(result))
```

**Comment by Ninju** [comment]
Just in case this is what you wanted, I've added it to npm: 

https://www.npmjs.com/package/reduce-stream-to-promise

and the Github link is on the page, but here's a lazy link: https://github.com/Ninju/reduce-stream-to-promise.

**Comment by RangerMauve** [comment]
Not sure why I didn't notice that sooner. It's pretty much perfect. Only issue is it won't work with async reduce functions, but that would warrant a separate library. Thanks!
