### ISSUE TITLE
Package to change the date and time setting of the OS

### ISSUE THREAD

**Issue by Whoaa512** [sindresorhus/module-requests#46]
Like the [wallpaper](https://github.com/sindresorhus/wallpaper) module but for the Date and Time settings

**Comment by Qix-** [comment]
This will quickly run into permissions issues, and could easily be achieved using a child process. :+1: Keep those things in mind.

**Comment by Whoaa512** [comment]
Found what I needed in the form of OSX and Linux cli tools

**Comment by sindresorhus** [comment]
@Whoaa512 Can you take the time to comment on what you found in case anyone else stumbles upon this issue?

**Comment by Whoaa512** [comment]
The trusty [`date`](http://unix.stackexchange.com/questions/151547/linux-set-date-through-command-line) command is available on most unix systems by default.
