### ISSUE TITLE
What's your time?

### ISSUE THREAD

**Issue by SamVerschueren** [sindresorhus/module-requests#47]
I was thinking about a small cli tool to retrieve the current time of a GitHub user. For example, @sindresorhus is located in Bangkok (or somewhere in Thailand) if I'm not mistaken. In terms of collaboration, it could be nice to know what his current time is.

```
$ time sindresorhus
3 Dec. 2015 - 18:52:32
```

But it's not possible to do this via an API (if I'm wrong, please tell me :)). So in order for this to work, everyone that wants to get "tracked" by this module, needs a `time` repository (or something else, as long as it is uniform) with a .timezone file.

```
Europe/Brussels
```

The `time` module will read and parse that information and shows the appropriate time. We can make a nice `README` file, like the [AMA](https://github.com/sindresorhus/ama) repositories explaining what it does. I can start it, and everyone can just fork it (just the same as in the AMA's).

--------------------------

Is this something you guys find usefull (or nice) to have? If no one cares, I probably won't do it (or maybe I will). Just wanted more thoughts on this.

// @sindresorhus @Qix- @kevva @vdemedes @arthurvr

**Comment by vdemedes** [comment]
I think this is a great idea!

2 things though. 

1. 'time' is already taken :D Run 'which time'
2. For implementation (tracking who's where), we need to come up with something simpler than creating a whole repo to set a timezone :)

**Comment by SamVerschueren** [comment]
Already thought it was taken, so naming ideas are also welcome :).

Creating one repository with `.SamVerschueren`, `.vdemedes`, ... isn't a good idea either. You always have to do a PR to update your timezone. Don't want to host a webservice for this and it should be easy to update your timezone.

```
$ time update
```

> I know, `time` is taken ;)

This can try to pull your repository, update the `.timezone` file and push it back to github. It will off course only work if the ssh keys are set up correctly.

**Comment by parro-it** [comment]
@vdemedes : 2. could be automated, if we call 
```bash 
$ time update
```
the cli could retrieve the current system timezone, ask for the GH user credential [(this module could be useful)](https://github.com/parro-it/git-credential-node), and either:

1) it create the repo if it doesn't exists
2) it update timezone info in existing repo if they are differents from current one

**Comment by parro-it** [comment]
@SamVerschueren ops, I got same idea as you :smiley:

**Comment by vdemedes** [comment]
I think the easiest and the most comfortable solution would be to use Firebase for storage (they have a free plan). We don't need their real-time features, just their key/value store.

**Comment by SamVerschueren** [comment]
@vdemedes What if firebase shuts down the free service? What if firebase shuts down entirely in 2 years? That's why I think we have to be as independent as possible.

Someone could also just fill the key/value store with crap. How are we going to detect that one user only pushes one value?

**Comment by vdemedes** [comment]
@SamVerschueren Haha, you are talking like it's going to be a startup :D It's pretty safe to assume Firebase won't shut down the free plan and if they will shut down entirely, we will just move the data somewhere else.

I'd advise to simplify things down, it's just a handy tool. If you are looking for a full-featured product, there are already existing (and pretty good) apps that do exactly that ;)

**Comment by SamVerschueren** [comment]
> Haha, you are talking like it's going to be a startup :D 

LOL

> I'd advise to simplify things down, it's just a handy tool.

Isn't a GIT repository way more simpler then a Firebase back-end? Never used it to be honest. But isn't it possible with a firebase back-end to have one user just fill up the entire free plan with crap?

```
$ time update -n 1
$ time update -n 2
...
```

The idea is to get the time by the GH username. Without an OAuth signup process, we can't manage that I guess. Wonder what other people think of the Firebase Vs. GitHub discussion :).

**Comment by hemanth** [comment]
We could use one from #18

**Comment by parro-it** [comment]
I think that using GitHub would be a better choose. Even if this module will not become a startup, I think that if it get used by many people someone could find funny to change someone other timezone. Also, if it will use Firebase, we'll have to store somewhere the GH username, or ask it everytime the user whant to change its current timezone...

**Comment by vdemedes** [comment]
For access control: https://www.firebase.com/docs/security/quickstart.html

**Comment by SamVerschueren** [comment]
> If no has started yet, I can do it, planning to call it dev-time what say?

@hemanth Would like to do it myself :), but happy to receive some PR's :).

@vdemedes Thanks for the information, will have a look at it. But as you already noticed, I'm a little bit skeptical against Firebase. I think it's a very nice product, but not sure if it fits this use case (not that GitHub is a good fit either probably :)). My major concerns are:
1. How would we make sure someone isn't writing a script to fill the entire KV-store with junk
2. How can we know for sure that `SamVerschueren` in the database, really is me on GitHub. Everyone can just provide the information that he wants.

**Comment by SamVerschueren** [comment]
Although, the initial thought was to retrieve the current time of the developer, it can be expanded for more information. This example is when I decide to go for GitHub (but you'll get the idea).

### Files
```js
.timezone
.mail
.hometown
```

#### .timezone
```
Europe/Brussels
```

#### .mail
```
sam.verschueren@gmail.com
```

#### .hometown
```
Bruges
```

### CLI example

Command could be something like `info` or `devinfo`.

```
$ info time -n SamVerschueren
//=> 4 Dec. 2015 - 09:39:20

$ info mail -n SamVerschueren
//=> sam.verschueren@gmail.com

$ info hometown -n SamVerschueren
//=> Bruges

$ info phone -n SamVerschueren
//=> `phone` not set
```

The user just sets what he wants. You don't want to expose your hometown, fine, don't :). Just some ideas.

**Comment by sindresorhus** [comment]
I think this could be very useful! I often have the need to find out when someone would be online or awake. I'm not sure about having to manually manage this, though. I would easily forget to update my `.time` file when traveling.

How about instead it used different services that already know my location?

- git, afaik git commits have the timezone: git log => `Date:   Mon Nov 30 14:05:44 2015 +0700`
- Swarm (I check-in there often)
- Facebook
- Twitter tweets (many of my tweets have location.

And then fall back to hardcoded stuff, like location in Twitter profile, location in GitHub profile, etc, when the above is not available.

**Comment by SamVerschueren** [comment]
@sindresorhus Apart from the first check (git commit), it assumes that the account name of Swarm, Facebook, Twitter is the same as GitHub. But I agree it would be a lot easier.

As to retrieving the timezone from git commits, there is no API for something like `git log`. It is possible to retrieve commits from a repository, but what repository should be checked if I want to know your time(zone)? And the date property in a commit is UTC (e.g. `2015-12-03T07:37:25Z`) so that API won't do the trick. Can't find any accessible API to retrieve that kind of information.

**Comment by SamVerschueren** [comment]
Will have a deeper look into the suggested methods and experiment a little. But if the module has to support all those API's, we have to embed API keys and stuff.

**Comment by sindresorhus** [comment]
@SamVerschueren I agree all of this isn't feasible. Just braindumping.

-

`git log` locally at least seem to preserve the timezone:

```
commit 29533a24e6c043ff3d0b07ad081e63e8d21c7076
Author: Sindre Sorhus <sindresorhus@gmail.com>
Date:   Fri Dec 4 17:42:57 2015 +0100

    tweaks

commit 995c8e19e357501029492fe9ea3637aa352bb928
Author: Sindre Sorhus <sindresorhus@gmail.com>
Date:   Tue Feb 17 12:22:29 2015 +0700
```

> As to retrieving the timezone from git commits, there is no API for something like git log

Uhm, `git`? http://stackoverflow.com/questions/1161869/how-to-get-sha-of-the-latest-commit-from-remote-git-repository

**Comment by SamVerschueren** [comment]
`git remote-ls` returns the hashes of the commits. But the only command that shows the commit time in the correct timezone is `git log`. Hacking some stuff together now, keep you posted on this, have some ideas :).

**Comment by Qix-** [comment]
Why not just query Github for the latest commit?

**Comment by parro-it** [comment]
I think the original idea of update a repo will be simple to develop. 
@sindresorhus sayd it probably will forget to update it: fine, one could just put the command in .zshrc or whatever autostart script she use...

**Comment by Qix-** [comment]
I feel there are security and privacy concerns making an HTTP request upon starting up your shell. As well, that would add considerable overhead to your shell prompt, especially if you have other stuff in there, upon starting up. We already have information regarding timezones people are in, as mentioned before. We should make use of those instead IMO.

**Comment by SamVerschueren** [comment]
I'm onto something here. Keep you posted.

**Comment by parro-it** [comment]
@Qix- uhm, you're right, I'm already annoyed by waiting my prompt, but every OS has way to run script on startup https://github.com/julianduque/node-autostart

**Comment by SamVerschueren** [comment]
Alright, so I'm getting closer, but not entirely. This is what I do so far

1. Use the GitHub API to retrieve information of the latest commit of a user
2. Clone the repository of that latest commit into a temporary directory
3. Run `git log` (with some formatting) to extract the timezone of that commit
4. Done!

BUT

When I tested this with @sindresorhus, I noticed he did some merges. No problem I thought, as in a merge you have a contributor and an author.

![screen shot 2015-12-04 at 22 19 13](https://cloud.githubusercontent.com/assets/1913805/11601726/7b619eaa-9ad5-11e5-985f-3e4676e71906.png)

Too bad the commit date does not take the timezone of the committer. Any ideas here?

**Comment by Qix-** [comment]
@SamVerschueren that is actually accurate. :+1:

**Comment by SamVerschueren** [comment]
@Qix- Is he back in Norway (GMT+1)?

**Comment by sindresorhus** [comment]
He is.

**Comment by SamVerschueren** [comment]
> He is.

LOL :)

Then my module works I guess. Will wrap it up tomorrow and throw it online.

**Comment by SamVerschueren** [comment]
Any feedback regarding a name for the thing? 

- `dev-time`
- `time-of`
- `current-time`
- ...

**Comment by hemanth** [comment]
I would indeed vote for [dev-time](https://github.com/sindresorhus/module-requests/issues/47#issuecomment-161751569) ;)

**Comment by sindresorhus** [comment]
`dev-time`

**Comment by Qix-** [comment]
`dev-time` for sure.

**Comment by SamVerschueren** [comment]
Released as [dev-time](https://github.com/SamVerschueren/dev-time-cli)

**Comment by sindresorhus** [comment]
Woot! :)

**Comment by hemanth** [comment]
:+1:

**Comment by SamVerschueren** [comment]
Thanks everyone for the feedback by the way!

**Comment by stevemao** [comment]
@SamVerschueren does the tool return the person's location as well? :)

**Comment by SamVerschueren** [comment]
@stevemao Nope, only the timezone. That information isn't stored by GitHub.

**Comment by stevemao** [comment]
Would be great if there is a way to include it :)

**Comment by stevemao** [comment]
I built http://dev-time.today a while ago. I think this is pretty handy when I can't use the cli. However I couldn't get any designer who's interested to make the site pretty 😭
The repo is here: https://github.com/stevemao/dev-time.today Please take a look :)
