### ISSUE TITLE
Text only GIF generator

### ISSUE THREAD

**Issue by beatfreaker** [sindresorhus/module-requests#48]
Text only GIF generator something like this : [Slate](http://bitshadow.github.io/slate/)

the idea is to make a CLI app which allows to generate such GIF images.

**Comment by egoist** [comment]
nice idea!

**Comment by beatfreaker** [comment]
Released [text-meme](https://github.com/beatfreaker/text-meme-cli)
```
npm install --global text-meme-cli
```

pleas share your though and help me in improving it.

Thanks

**Comment by sindresorhus** [comment]
Nice! I opened a pull request and some issues ;)

**Comment by beatfreaker** [comment]
Thanks for the review :)

**Comment by hemanth** [comment]
Nice one, I have a half baked [web](https://github.com/hemanth/make-quote) version, if anyone wants to paw it ;)
