### ISSUE TITLE
Google Inbox desktop app using Electron

### ISSUE THREAD

**Issue by stephenplusplus** [sindresorhus/module-requests#49]
That is, a standalone Inbox application.

There is a project which does just this, [gInbox](https://github.com/chenasraf/gInbox), but it seems relatively unmaintained. It does the job, but the most important feature that is missing is alerts of new messages.

**Comment by SamVerschueren** [comment]
:+1:

**Comment by Qix-** [comment]
I would recommend forking `gInbox` rather than adapting Caprine. Inbox is already pretty UI-ready, and a lot of thought went into that. All `gInbox` seems to be is an electron (or nwjs or something) wrapper around the site. You're not going to achieve much in the line of "advancement" by using a desktop wrapper.

Have you tried [thunderbird](https://www.mozilla.org/en-US/thunderbird/)?

**Comment by stephenplusplus** [comment]
Isn't Caprine a wrapper around Facebook Messenger? Maybe I misunderstood and it's more than that.

The most important feature (imo) that's missing from gInbox is the notifications when a new message arrives (a badge, a system notification, anything). Forking is cool, but then the benefit of cross-platform is lost, as gInbox is written in Swift.

**Comment by Qix-** [comment]
> Isn't Caprine a wrapper around Facebook Messenger? Maybe I misunderstood and it's more than that.

It is. Facebook Messenger and Google Inbox are wildly different infrastructures.

> Forking is cool, but then the benefit of cross-platform is lost, as gInbox is written in Swift.

Whoops, for some reason I thought I glanced up and saw yellow (for Javascript). This could easily be achieved with electron and a few extra packages.

**Comment by sindresorhus** [comment]
> Isn't Caprine a wrapper around Facebook Messenger?

Yes, it just wraps https://messenger.com and adds notifications, and some native menues.

**Comment by stephenplusplus** [comment]
> Facebook Messenger and Google Inbox are wildly different infrastructures.

Is there something I'm not thinking about that an Inbox wrapper will need to do that is more difficult? Still just want notifications :)

**Comment by Qix-** [comment]
@sindresorhus doesn't caprine use an API? Or is it just a literal webkit wrapper that points to messenger.com?

**Comment by sindresorhus** [comment]
> Or is it just a literal webkit wrapper that points to messenger.com?

:arrow_up:

**Comment by Qix-** [comment]
Ah then Caprine could do it. Disregard me.

**Comment by stephenplusplus** [comment]
Oh, look at this: http://www.boxyapp.co/

**Comment by SamVerschueren** [comment]
It's OS X only...

**Comment by stephenplusplus** [comment]
Yep.

**Comment by parro-it** [comment]
Now there is [wmail](https://github.com/Thomas101/wmail). Just started to use it, looks promising....

**Comment by sindresorhus** [comment]
Also: https://github.com/fgnass/inbox-app

**Comment by zusamann** [comment]
Sorry a bit late to the party but this library here https://github.com/jiahaog/nativefier
Can convert any web app into an electron app.

**Comment by forivall** [comment]
also wavebox.io
