### ISSUE TITLE
Image upload CLI

### ISSUE THREAD

**Issue by egoist** [sindresorhus/module-requests#51]
We can drag and drop an image to the terminal, press enter, uploading, return the URl the uploaded image.

Or drag and drop a folder into terminal, automatically uploading the images inside.

**Comment by sindresorhus** [comment]
Something like https://github.com/Automattic/cloudup-cli. What service should it upload to?

**Comment by hemanth** [comment]
Why should one drag and drop to a terminal, when you can easily give the path to it.

**Comment by egoist** [comment]
This is more like a tool to shared random images, no account needed, no worry about the remaining spaces. Like writing a Jekyll-hosted blog, I don't even want to store post images in my own cloud.

I always use GitHub issues to upload random images and share the link of it elsewhere.

`Cloudup` is sure good for stuffs that need to be collected.

So I just made a half baked version to fill my own need. https://github.com/egoist/image-cli

**Comment by Qix-** [comment]
Github isn't a great place for mirroring images. I'd use [Imgur](http://imgur.com) for that.

**Comment by egoist** [comment]
:+1: Imgur is great, but it's totally blocked in China.

**Comment by Qix-** [comment]
@egoist oh that's a shame, sorry to hear that.

**Comment by forivall** [comment]
or https://github.com/crescentrose/puush4linux

**Comment by Mithgol** [comment]
You may also try a CLI of some P2P-distributed file system (such as [IPFS](https://ipfs.io/) and its `ipfs add` command).

It would look like the following:

![(screenshot)](https://cloud.githubusercontent.com/assets/1088720/18287130/77c042be-747e-11e6-9bdf-9b4ce85862f5.gif)

And the added file is at https://ipfs.io/ipfs/QmY9QSyyfSr7ChXz8UmWkPAGdCu1sj85TS1F4yPqb5STUz now.
