### ISSUE TITLE
Automatically detect missing dependencies and run npm install under the hood

### ISSUE THREAD

**Issue by egoist** [sindresorhus/module-requests#52]
When we are just typing `import test from 'ava'`  in our favorite editor, it auto detects if this module is installed in `cwd`, if not a `npm install ava` command will be excuted for us.

**Comment by sindresorhus** [comment]
https://github.com/hughsk/atom-npm-install

**Comment by egoist** [comment]
Hope to have a Sublime port of this. 😙
