### ISSUE TITLE
Awesome list of small, focused, npm modules 

### ISSUE THREAD

**Issue by parro-it** [sindresorhus/module-requests#56]
I have started an awesome list of small focused modules. I don't know if this is an appropriate place to present it, I just think it could became a useful reference for searching existing modules.

You can find at [this repo](https://github.com/parro-it/awesome-microlibs).

**Comment by forivall** [comment]
I don't know how often it gets updated, but there's already http://microjs.com/

**Comment by parro-it** [comment]
Yes, I know that site, but I want to include only repos that are really focus (ideally one exported function only). Microjs.com list libraries like underscore or backbone, that I don't really consider "micro". Moreover, I want to use the awesome style for the repo, I think it could ease the collaboration process.

**Comment by sindresorhus** [comment]
I like it. Not sure how you're gonna judge what's added and not, though. There are thousands and thousands of small focused modules on npm. Most of mine (hundreds) are small and focused, and I'm just one person.

**Comment by parro-it** [comment]
Glad you like it, @sindresorhus. 
By now, I've add modules I personally use in my day to day work. 

Primary criteria to choose new entries will be in general to be awesome (good tests, readme, etc.).

I just refused a [first submission](https://github.com/parro-it/awesome-microlibs/pull/1) that doesn't meet  this criteria.

Your hundreds or small modules probably fits all, I honestly don't know at the moment what to do if you submit them all :smile:

**Comment by parro-it** [comment]
Please don't, at least not all together :smile_cat:

**Comment by sindresorhus** [comment]
Yeah, I'm not going to. Prioritize others modules. Just saying. There's a LOT out there. Figure out a process to handle submissions.

**Comment by parro-it** [comment]
I'll do. I need to improve the contributing.md file, at least specifying that modules must meet some minimum criteria to be approved (good tests, readme, usage in production etc.). 

I will submit the list to [awesome list](https://github.com/sindresorhus/awesome) within some week...
