### ISSUE TITLE
space-hogs: cli for discovering surprisingly large directories

### ISSUE THREAD

**Issue by dylang** [sindresorhus/module-requests#59]
## Example Situation

You'd like to quickly discover that a dependency in your `node_modules` is 45 MB larger than the rest, which are all a few KB. Or to just figure out why your HD is more full than you were expecting.

## How the tool works

1. Use `du -sh` or something like it to find the recursive size of each child directory.
2. Compare the results. If any are significantly larger than the rest, drill into those dirs and repeat. *Stop recursively drilling down when the individual sub directories are not of significant size.*
3. Output the paths and space used, and % overall, of the largest directories.

## Example

```
my-project > space-hogs
45 MB  50%  node_modules/foo/node_modules/bar/bower_components
30 MB  48%  docs/videos/raw
 1 MB   2%  Everything Else
```

## Similar Tools

* [WinDirStat](https://windirstat.info/) - Windows only, GUI only, shows every directory, not just the largest offenders.
* [Grand Perspective](http://grandperspectiv.sourceforge.net/) - Mac only, GUI only, shows every directory, not just the largest offenders.

**Comment by forivall** [comment]
FYI: WinDirStat is based on [KDirStat](http://kdirstat.sourceforge.net/) (-> [QDirStat](https://github.com/shundhammer/qdirstat))

**Comment by verth** [comment]
If anyone is interested in this, I just threw a very basic version together in a gist. It recursively goes through the directories and lists the folders with their sizes. Folders that get drilled in deeper or are an endpoint will show in green. 

You can filter on outliers, by largest or write a new function that takes an array of directories and returns a filtered array.

https://gist.github.com/verth/053937d43c241ba5ba98

Example:

```
$ node index.js
240136 | ./assets/
330113 | ./node_modules/
1368502 | ./public/ **
-------------------
45061 | ./public/css/
1323441 | ./public/img/ **
-------------------
```

**Comment by sindresorhus** [comment]
:+1: Looks useful. Someone make this! :)

https://github.com/sindresorhus/pretty-bytes could be useful for this.

**Comment by Qix-** [comment]
Something to think about - which directory do you report as being "big"? What constitutes as "big"? What's the margin?

Perhaps a tree-like output with sorted directories (by size) and the human-readable sizes would be super effective. Perhaps if I _know_ a directory is going to be big - and that's okay - but there's other unaccounted-for space that's being taken up in another directory, I don't want that first directory being the only one shown.

Just a thought.

**Comment by ewnd9** [comment]
Take a look at [ncdu](http://linux.die.net/man/1/ncdu) (available at least on linux). Looking like exactly what you want

![2016-02-11t13 53 30 824z](https://cloud.githubusercontent.com/assets/1713789/12978124/ad2cd564-d101-11e5-8af6-1c1287e583f4.gif)

**Comment by Qix-** [comment]
`brew install ncdu` appears to work on OS X. I'll give it a try. Thanks @ewnd9 :)

**Comment by forivall** [comment]
And from a quick google search (not on windows rn), it appears to be available [in cygwin](https://cygwin.com/cgi-bin2/package-cat.cgi?file=x86_64%2Fncdu%2Fncdu-1.10-1&grep=ncdu) and [in msys](https://github.com/goreliu/my-MSYS2-Packages/tree/master/ncdu)

**Comment by sindresorhus** [comment]
@dthree Could it be beneficial to use [vorpal](https://github.com/dthree/vorpal) here for interactivity?

**Comment by dthree** [comment]
For sure! Would be pretty easy for something to throw something like ncdu together in Node.

**Comment by backspaces** [comment]
I like OmniDisksweeper: https://www.omnigroup.com/more (Mac only, alas)
.. but would love a cli for scripts, both local and on servers.

**Comment by addyosmani** [comment]
I wouldn't mind working on this unless someone else really wants to take it.

**Comment by dthree** [comment]
:+1: on Addy taking it!

**Comment by dylang** [comment]
I've started working on it @addyosmani, want to work together? I'll push what I have to Github today.

**Comment by dylang** [comment]
@sindresorhus @dthree @addyosmani and friends: here is my take on my own module request:

### Install

```
$ npm i -g space-hogs
```

### Usage

```
space-hogs --help

  Discover surprisingly large directories.

  Usage
    space-hogs [path] [size] [--depth=number]

  Options
    directory        Directory to scan. Defaults to the current directory.
    size             Minimum size in MB. Defaults to 6% of the total MB.
    --depth=number   Number of sub-directories to dive into. 0 = none. Defaults to all.

  Examples

    $ space-hogs
    $ space-hogs node_modules 5 --depth=0
    $ space-hogs 1000
```

### Example

```
~/projects/npm $ space-hogs
151 MB ~/projects/npm
Largest children directories, each larger than 9 MB
├──  31 MB [▒   ] /.git
├──   9 MB [▒   ] /node_modules/npm-registry-couchapp/node_modules
├──  12 MB [▒   ] /node_modules/tap/node_modules/nyc/node_modules
├──  20 MB [▒   ] /node_modules/standard/node_modules/standard-engine/node_modules/eslint/node_modules
├──  17 MB [▒   ] /node_modules/standard/node_modules/standard-format/node_modules/esformatter-jsx/node_modules/babel-core/node_modules
└──  62 MB [▒▒  ] (everything else)
    151 MB Total
```

### Contribute

https://github.com/dylang/space-hogs

**Comment by dylang** [comment]
If you tried [space-hogs](https://github.com/dylang/space-hogs) when I first posted it a 7 hours ago and it didn't work, try again. It now supports `du` implementations from both BSD (OS X's default) and GNU (such as `brew install coreutils`), and gets the same results with either.  

```bash
$ npm i -g space-hogs
```

Thanks go to @backspaces for the [quick bug report](https://github.com/dylang/space-hogs/issues/1). :smile:

**Comment by dylang** [comment]
I'm closing this as [space-hogs is available to use](https://github.com/dylang/space-hogs). 

Any further discussion can be created as an issue with `space-hogs`. 

Thanks everyone for your ideas and suggestions, I hope the tool has been useful!
