### ISSUE TITLE
Cross-OS library to tell which desktop window has focus

### ISSUE THREAD

**Issue by serapath** [sindresorhus/module-requests#67]
There are apps like:
- https://www.rescuetime.com/
- http://www.manictime.com/
- http://focuslist.co/escape/?ref=producthunt
- https://wakatime.com/dashboard
- http://darcs.nomeata.de/arbtt/doc/users_guide/

...and many more. Those enable you in different ways to log what you do on the computer.
I don't even know what start looking for. In case something already exists that allows me to get some information about running desktop apps and open documents in case it's an app that allows that, like editors or browsers, that would be neat. In case it doesn't it would be neat if a module that gives that information fires an event onfocus. :-)

**Comment by sindresorhus** [comment]
I made a module for this a couple of months ago, but never got around to publishing it. Just did so now. It's OS X only, but PR welcome for Linux and Windows support.

https://github.com/sindresorhus/active-win

-

I'll keep this open in case anyone wants to contribute or have something that works cross-platform.

**Comment by serapath** [comment]
:+1: cool :-)

**Comment by Richienb** [comment]
@serapath `active-win` is now cross-platform.

To get the name of the active window, you can do this:

```js
const activeWin = require('active-win');

(async () => {
	const { title } = await activeWin();

	console.log(`The active window is: ${title}.`)
})();
```

@sindresorhus You can close this issue now.
