### ISSUE TITLE
Module to resolve a module path from caller module.

### ISSUE THREAD

**Issue by parro-it** [sindresorhus/module-requests#68]
I want to write a module for `electron` to circumvent [this electron issue](https://github.com/electron/electron/issues/5090). TLDR is that electron `remote.require` does not allow to require modules relative to the current one. They are always relative to the main process module.

To do this, I need to resolve a module absolute path relative to caller directory.

I think it could be easily done using `sindresorhus/caller-callsite` to get the dir path of the caller,
and then `sindresorhus/resolve-from` to resolve the module full path from there.

Anywhere, are you aware of some existing module that already do this? I did some research on NPM but without luck...

**Comment by sindresorhus** [comment]
See: https://github.com/sindresorhus/parent-module#tip

**Comment by parro-it** [comment]
Thank you. Seems a better choice. Meanwhile, I found https://github.com/fengb/module-resolve-as-caller that does exactly what I need. Only, it uses path.resolve for the resolution part, I think by mistake. I will provide a PR there...
