### ISSUE TITLE
Get the user's e-mail address

### ISSUE THREAD

**Issue by sholladay** [sindresorhus/module-requests#69]
This is in the spirit of [fullname](https://github.com/sindresorhus/fullname), but for an e-mail address. The primary use case for me would be to provide a great `default` within a Yeoman generator prompt for project scaffolding.

The order of precedence would be:

1. `git config user.email` (prefer local, fallback to global)
2. `npm config get init.author.email` (exits 0 with "undefined" if unset, though...)
3. [npm-email](https://github.com/sindresorhus/npm-email), based on the output from `npm whoami`.
4. Other [shenanigans](https://github.com/paulirish/github-email/blob/master/github-email.sh).

**Comment by verth** [comment]
Hi, cool idea! I started this today, your functions 1-3 are working, see here [npm](https://www.npmjs.com/package/user-email) - [github](https://github.com/verth/node-user-email) :+1:.

I'll look to improve it, lint and test it, and add more email-checkers. It's pretty basic now and improvements are greatly appreciated.

**Comment by sholladay** [comment]
Awesome, thank you. Looks like a good start. I will kick the tires this weekend.

**Comment by pgAdmin** [comment]
@sindresorhus  I think this can be closed.
