### ISSUE TITLE
separate is-server-accessible from is-online

### ISSUE THREAD

**Issue by dylang** [sindresorhus/module-requests#7]
Take [the core of is-online](https://github.com/sindresorhus/is-online/blob/master/index.js#L23-L83), and make a separate module that has as input `server` and returns a promise or callback if it can be reached or not.

This is useful for looking for a certain server that your airplane, office, or country might block, or checking to see if you are on your corporate vpn before trying to access servers behind the firewall.

`is-online` would use this new module.

**Comment by sindresorhus** [comment]
Good idea! Keep 'em coming :D

https://github.com/sindresorhus/is-reachable

**Comment by arthurvr** [comment]
Awesome!

**Comment by hemanth** [comment]
:+1:

**Comment by dylang** [comment]
Amazing, thanks @sindresorhus!
