### ISSUE TITLE
Command to minimize all open windows and show desktop from the terminal

### ISSUE THREAD

**Issue by iamtekeste** [sindresorhus/module-requests#70]
https://github.com/iamtekeste/sd-cli

**Comment by sindresorhus** [comment]
What are you requesting exactly?

**Comment by djyde** [comment]
If you are using OS X, just...

![osx](https://cloud.githubusercontent.com/assets/914329/14761157/8e46588e-098a-11e6-9c03-6c29bd7e2fc8.gif)

**Comment by egoist** [comment]
@djyde <kbd>Command</kbd> + <kbd>Alt</kbd> + <kbd>H</kbd> + <kbd>M</kbd>

**Comment by iamtekeste** [comment]
I am just showing off what I made :) . Closing!
