### ISSUE TITLE
Node bindings for libui, an awesome native UI library for Unix, OSX and Windows

### ISSUE THREAD

**Issue by parro-it** [sindresorhus/module-requests#72]
Hi all, I started a project to write node bindings for [libui](https://github.com/andlabs/libui).
`libui` is a C library that implements a multiplatform native GUI toolkit for OSX, Windows and Unix.

https://github.com/parro-it/libui-node

It could become a lightweight alternative to Electron for projects that doesn't need all the web platform super-powers, libui binaries size is only ~ 300k!

Here are some screenshot from the libui repo:

![Windows](https://raw.githubusercontent.com/andlabs/libui/master/examples/controlgallery/windows.png)

![Unix](https://raw.githubusercontent.com/andlabs/libui/master/examples/controlgallery/unix.png)

![OS X](https://raw.githubusercontent.com/andlabs/libui/master/examples/controlgallery/darwin.png)

I implemented almost all of `libui` API, but I would need help, feedback and suggestions from anyone interested.

Any help is greatly appreciated, from PR to simple tweaks or corrections...

Furthermore, I'm planning to implement a set of JSX compatible API on top of this one, and next a react-native like framework...

Thank you!

**Comment by ewnd9** [comment]
That's a great idea

> It could become a lightweight alternative to Electron for projects that doesn't need all the web platform super-powers, libui binaries size is only ~ 300k!

Although `libui` size is small you need to take into consideration that in order to be really an alternative to Electron there should be an installer or a binary packager to be able to distribute applications without relying on installed `npm` and `node` on users machines. What do you think?

> next a react-native like framework...

You could implement your own react-renderer like [react-blessed](https://github.com/Yomguithereal/react-blessed) or [react-hardware](https://github.com/iamdustan/react-hardware)

**Comment by parro-it** [comment]
> Although libui size is small you need to take into consideration that in order to be really an alternative to Electron there should be an installer or a binary packager to be able to distribute applications without relying on installed npm and node on users machines. What do you think?

There is already some packager for npm: [nexe](https://github.com/jaredallard/nexe), [enclosejs](http://enclosejs.com/). However, I never used them. 
Both have some limitation, the most prominent being that they cannot package native node module, so you'll get one executable file with your app and node within, plus a node_modules folder containing native modules.

> You could implement your own react-renderer like react-blessed or react-hardware

I was thinking something similar... anyway, this will happen in future time, first I want to make libui-node stable. Libui itself is in alpha stage, so I expect there will be a lot of work to implement new `libui` API and to change existing ones.

A great help come from [nbind](https://github.com/charto/nbind) that really simplify the native addon building.

**Comment by sindresorhus** [comment]
This is really awesome! Great work @parro-it :)

**Comment by parro-it** [comment]
Thank you @sindresorhus, I'm glad you like it :smiley: 
I'm actually working to improve the install process, I will publish a first version on npm soon.

**Comment by parro-it** [comment]
I drafted some pages to document libui-node:

https://github.com/parro-it/libui-node/tree/master/docs …

It would be beautiful to get feedback/suggestions/corrections by the community

**Comment by PaulBGD** [comment]
I didn't know about this issue, just wanted to announce I'm working on a react renderer right now. If you're interested in contributing, send an email to paul@burngames.net
It's currently private, but I'm hoping to document it all soon and make a public release.
