### ISSUE TITLE
Have a good "printing area" package?

### ISSUE THREAD

**Issue by thearabbit** [sindresorhus/module-requests#75]
Have a good "printing area" package?

**Comment by SamVerschueren** [comment]
Could you be more precise in what you mean with `printing area`? Do you want to extract parts of a website to an image? [pageres](https://github.com/sindresorhus/pageres) can do that for you. Or is it something else you want? The more information you provide, the more likely people are able to help you ;).

**Comment by thearabbit** [comment]
I do the report, for example (one page)
```js
// Repor Form
Date : ..................
Branch : ...............
[Submit Btn]

[Print]
-----------------

// Report View
............

**Comment by leocaseiro** [comment]
Isn't CSS better for this?

**Comment by SamVerschueren** [comment]
Sorry, but that information is not enough to be able to help you out on this. You have to understand that you can't explain a problem or a use case in 14 words.

Go and have a look at other modules requested in the issue list. A lot of them have images to clarify what they want, they have links to packages related to the problem, etc. Opensource is not much different from real world customers. If a customer steps up to a company and wants an application, it's up to the customer to provide the company with enough information to make sure the company builds what the customer wants. This is no different. The more information you provide, the more likely it is someone will build it or come up with a solution.

So please, try again and write everything down step by step. Add screenshots (if helpfull), snippets, ...
