### ISSUE TITLE
Better search for awesome list

### ISSUE THREAD

**Issue by egoist** [sindresorhus/module-requests#82]
It's kinda hard to browse a long list like https://github.com/enaqx/awesome-react and even harder to find something you want quickly, maybe a public API or tool for searching this kind of **awesome list** can be cool?

For example, like https://react.parts but suits most awesome lists

**Comment by sindresorhus** [comment]
Already exists: https://awesomelists.top/#/repos/enaqx/awesome-react (There are more sites I don't remember right now), but I personally don't really see the point. You can already search with Cmd+F, and Awesome lists are more for discovery than searching anyways.

**Comment by zcuric** [comment]
@Akryrum made [awesomejs.dev](https://awesomejs.dev/)

**Comment by vladimyr** [comment]
> @Akryrum made [awesomejs.dev](https://awesomejs.dev/)

Wait a second. This looks like [react.parts](https://react.parts) with more javascript project types supported. But it has absolutely nothing to do with awesome lists in general. 

All awesome lists are plain old git repos with all the data contained inside `readme.md` or some other markdown file. OTOH [react.parts](https://react.parts) are curated through [github issues](https://github.com/jscoach/support/blob/master/CONTRIBUTING.md#how-do-i-add-a-package) and [awesomejs.dev](https://awesomejs.dev) is curated through on-site form: https://awesomejs.dev/pkg/add
Both use algolia search service and aren't really <kbd>Cmd/Ctrl</kbd>+<kbd>F</kbd> friendly...

Let's not mix apples and oranges. If @egoist is satisfied with a fact that [awesomejs.dev](https://awesomejs.dev) is curated differently than standard awesome list and if it covers his needs then it should be accepted as a valid answer, if not this should be reopened.
I don't see how the selected tool helps me in searchin' through [Awesome Rust](https://github.com/rust-unofficial/awesome-rust#readme). Ok @sindresorhus mentioned I could use https://awesomelists.top/#/repos/rust-unofficial/awesome-rust but to be completely honest (no offense to anyone) it is so ugly that I simply can't stand looking at it 🤷‍♂

**Comment by sindresorhus** [comment]
@vladimyr I closed this because of my previous comment. This already exists. Not because of https://github.com/sindresorhus/module-requests/issues/82#issuecomment-590111561.

There's also: https://www.prettyawesomelists.com/lists/github/rust-unofficial/awesome-rust

**Comment by vladimyr** [comment]
Oh, I got it wrong, thx for explaining 👍

FWIW https://awesomelists.top/ is opensource: https://github.com/lockys/awesome-search while I couldn't easily find the source code for https://prettyawesomelists.com
And you are absolutely right, native search is stellar technology compared to this...
