### ISSUE TITLE
chalk-animation

### ISSUE THREAD

**Issue by Kikobeats** [sindresorhus/module-requests#95]
![](https://user-images.githubusercontent.com/170270/27715291-8106fa38-5d36-11e7-9623-47bfc5e9cca3.gif)

Now with true color support at chalk 2.0 could be awesomeness a module for create simple terminal colors animations like:

- rainbow (of course!)
- lineal gradient
- loading/karaoke
- pulse/heartbeat
- neon
- need more ideas (?)

**Comment by bokub** [comment]
Great idea! Do you think it should be part of chalk, or a completely different module?

**Comment by Kikobeats** [comment]
@bokub I think chalk is tiny and focused, this is more for fun and need to alive in a different but complementary package.

**Comment by bokub** [comment]
I never heard of chalk before to be honest. Am I wrong or chalk doesn't support gradients?

**Comment by bokub** [comment]
I'm working on it.

**Comment by Qix-** [comment]
FWIW that example is in the `examples/` directory in the chalk project.

**Comment by bokub** [comment]
So I've created a package called [chalk-animation](https://github.com/bokub/chalk-animation) which can output this animated rainbow.
 The animations can be stopped and resumed, and the speed is customizable.

As I needed to output gradients in the terminal, I have also created [gradient-string](https://github.com/bokub/gradient-string), which I use in chalk-animation.

Currently, only the _rainbow_ and the _pulse_ effect are available, so don't hesitate to add new animations and submit your pull requests! 👍

**Comment by sindresorhus** [comment]
@bokub Nice work!

The readme needs some animated GIFs of the effects though. Users are visual creatures.

**Comment by bokub** [comment]
@sindresorhus Done! Check it out [here](https://github.com/bokub/chalk-animation)

**Comment by sindresorhus** [comment]
Sexy! Can you do a pull request adding a link to it in the Chalk readme? (The related section)
