### ISSUE TITLE
Browser extension: Format JS code blocks with Prettier

### ISSUE THREAD

**Issue by fregante** [sindresorhus/module-requests#99]
> I often get comments on my repos with some example code from a user and the code is close to unreadable because of bad formatting. Would be nice to have [Prettier](https://github.com/prettier/prettier) run on JS code blocks in comments.
> 
> Not entirely sure how we can have it syntax highlighted again after the formatting though.
> @sindresorhus in https://github.com/sindresorhus/refined-github/issues/480

It exists a GitHub App for your own repos (https://github.com/jgierer12/prettier-github) but it might be useful as a browser extension.

**Comment by sindresorhus** [comment]
This could be useful for any code block on the web, not just on GitHub.

**Comment by bfred-it** [comment]
Generally the problem I've found is that sometimes _broken_ code blocks also lack the "js" attribute, and Prettier can only handle that

**Comment by sindresorhus** [comment]
I've often encounter blog posts with code examples using a bad and inconsistent code style, but is still correctly syntax highlighted.

**Comment by Haroenv** [comment]
Maybe that can be solved with a button to format code when needed in case the language mode isn't specified

**Comment by wasd171** [comment]
I have created a very raw [implementation](https://github.com/wasd171/prettier-chrome), it basically reformats every `<code></code>` it can find

**Comment by ritz078** [comment]
It will be great if this extension exists for firefox and safari also. You can use https://github.com/EmailThis/extension-boilerplate for that.

I had started to build it but found that @wasd171  already doing it. So I thought I will just share the ideas I had. 

- if language-* class exists take language form there.
- I tried to auto detect language using highlight.js but found that most of the times it fails.
- Only format `<pre><code></code></pre>` as only `<code></code>` won't require formatting.
- Give a small button to disable button on the top right corner of each code block.

I have no idea how to get the language of code if its not available. So maybe in that case we can give a select box at the top right of the code block to select from prettier supported languages or just the `popup.html` can be used to select a language to apply to whole page. Most of the times whole page contains the same code language.

**Enhancement** : Support code highlighting using highlight.js. It can be easily detected most of the times if the code is syntax highlighted or not using the HTML tags in the code block.

@wasd171 Let me know if you need any help. 
Others feel free to add any ideas.

**Comment by wasd171** [comment]
@ritz078 Thank you for your ideas! Unfortunately I am in the middle of my finals (for the whole August), so I can't actively contribute. 

Right now it tries to reformat the code and keeps the original if prettier fails with error. Does prettier autodetect the language? If so, perhaps it would be possible to extract this information afterwards?

Modifying Medium-style code blocks looks hard, it is probably needed to parse the HTML structure to get the code string. But perhaps if a such two-way parser can be created, afterwards the extension can fill formatted HTML back and get "native" highlighting.

**Comment by Mottie** [comment]
This can be done using the [Prettier GitHub App](https://github.com/apps/prettier-github) in the marketplace. Oddly, I can't find the app while searching the marketplace.

**Comment by mrchief** [comment]
Prettier is pretty biased. Formatting code with it can lead to code looking different than what is in the actual source. Or am I missing something here?

**Comment by Mottie** [comment]
> Modifying Medium-style code blocks looks hard

I created a [Darker-Medium](https://github.com/Mottie/Darker-Medium) extension that formats code blocks. All I had to do was target all `.section-content pre`, add a `prettyprint` class and call Google Prettify ([source](https://github.com/Mottie/Darker-Medium/blob/master/js/content.js#L219-L227)); because of the way the HTML is formatted, you can't include line numbers. I think it would have been much harder with prettier.
